### ISSUE TITLE
Consumer client running in to a deadlock

### ISSUE THREAD

**Issue by vsrini-ns** [dpkp/kafka-python#2077] opened 2020-07-11 03:04 UTC
**Problem Details**

We are seeing a deadlock situation with the Kafka consumer especially when the Group Coordinator is not reachable for a period of time larger than the request timeout. The heartbeat thread and the AsyncClient are waiting for each other to release the lock.

Based on the analysis, it appears there is a race condition for the deadlock to happen between the heartbeat thread and the Async client especially when the consumer group coordinator is not reachable beyond the maximum request timeout limit. 

A combination of parallel execution of the heartbeat request, broker connection timeout and the cancellation of the any pending in-flight requests when the consumer group coordinator is not reachable could lead us to this situation.

**Branch:** Kafka-Python 1.4.7

**Consumer Properties**
```
{'bootstrap_servers': ['kafka01:9092', 'kafka02:9092', 'kafka03:9092', 'kafka04.:9092', 'kafka05:9092', 'kafka06:9092'], 'enable_auto_commit': True, 'session_timeout_ms': 60000, 'max_poll_records': 100, 'group_id': 'deadlock-test'}
```
**From the Logs**
```
1) Consumer is polling continuously 
2) Heart Beat is failing (unable to talk to group coordinator) - coordinator is marked dead
3) Heartbeat session expired, marking coordinator dead 	
(00:45:55.498 -0700 to 00:49:56.374 -0700)
4) Auto offset commit failing continuously (NodeNotReadyError), while poll(..) is able to fetch records
   - 00:45:10.520 -0700 to 00:50:03.251 -0700
5) Async client connection is closed after the request timeout is elapsed (timed out after 305000 ms. Closing connection)
   - 00:50:03.253 -0700
```

**Code Analysis**
```
ConsumerGroup.Poll()	
	-> Consumer.Poll()  
		-> Activates Heart Beat Thread to send heart beat							HeartBeat Thread
		-> CommitOffsetAsync                                      							-> lock()
			-> AsyncClient.poll()												-> AsyncClient.poll() 
				-> lock()													-> monitor.lock() (waiting for CommitOffsetAsync to release lock)
					-> _poll()
						-> conn.close(error) [ Close All Request Timeout Connections ]
							-> Iterates In-Flight requests and associated callbacks
								-> Executes Callbacks in loop
									-> HandleHeartBeatFailure   			HandleHeartBeatFailure()
																-> lock() --> (waiting for heartbeat thread to release the lock)

```

**Thread Dump**

```
********************************************************************************
* Threads
********************************************************************************
Thread 0x7f998fb37700 (idle threadpool worker)

********************************************************************************
Thread 0x7f99974e1700 (None) (CURRENT)

  File "/opt/ns/python-apps/agent/app-env/lib/python3.7/site-packages/agent/pkg/utils/monitor.py", line 98, in check_kafka_offset
    print_greenlet_stacktrace()
  File "/opt/ns/python-apps/agent/app-env/lib/python3.7/site-packages/agent/pkg/utils/utils.py", line 26, in print_greenlet_stacktrace
    gevent.util.print_run_info(file=fd)
  File "/opt/ns/python-apps/agent/app-env/lib/python3.7/site-packages/gevent/util.py", line 99, in print_run_info
    limit=limit)
  File "/opt/ns/python-apps/agent/app-env/lib/python3.7/site-packages/gevent/util.py", line 152, in format_run_info
    _format_thread_info(lines, thread_stacks, limit, current_thread_ident)
  File "/opt/ns/python-apps/agent/app-env/lib/python3.7/site-packages/gevent/util.py", line 190, in _format_thread_info
    lines.append(''.join(traceback.format_stack(frame, limit)))

********************************************************************************
* Greenlets
********************************************************************************
---- Thread boundary
<greenlet.greenlet object at 0x7f9994e7b310>
 :    Parent: None
 :    Running:
 :      File "/opt/ns/python-apps/agent/app-env/bin/agentv2.py", line 55, in <module>
 :        agent.run()
 :      File "/opt/ns/python-apps/agent/app-env/bin/agentv2.py", line 49, in run
 :        self.kafka_consumer.run(self.repo_manager.message_handler)
 :      File "/opt/ns/python-apps/agent/app-env/lib/python3.7/site-packages/agent/pkg/kafka_consumer/kafka_consumer.py", line 41, in run
 :        self._retrieve_message_with_retry()
 :      File "/opt/ns/python-apps/agent/app-env/lib/python3.7/site-packages/agent/pkg/kafka_consumer/kafka_consumer.py", line 116, in _retrieve_message_with_retry
 :        messages = self._consumer.poll(timeout_ms=1000)
 :      File "/opt/ns/python-apps/agent/app-env/lib/python3.7/site-packages/agent/pkg/misc/kafkawrapper/consumer.py", line 369, in poll
 :        topic_partitions_messages = self._consumer.poll(**kwargs)kafkawrapper
 :      File "/opt/ns/python-apps/agent/app-env/lib/python3.7/site-packages/kafka/consumer/group.py", line 645, in poll
 :        records = self._poll_once(remaining, max_records, update_offsets=update_offsets)
 :      File "/opt/ns/python-apps/agent/app-env/lib/python3.7/site-packages/kafka/consumer/group.py", line 665, in _poll_once
 :        self._coordinator.poll()
 :      File "/opt/ns/python-apps/agent/app-env/lib/python3.7/site-packages/kafka/coordinator/consumer.py", line 290, in poll
 :        self._maybe_auto_commit_offsets_async()
 :      File "/opt/ns/python-apps/agent/app-env/lib/python3.7/site-packages/kafka/coordinator/consumer.py", line 806, in _maybe_auto_commit_offsets_async
 :        self._commit_offsets_async_on_complete)
 :      File "/opt/ns/python-apps/agent/app-env/lib/python3.7/site-packages/kafka/coordinator/consumer.py", line 473, in commit_offsets_async
 :        self._client.poll(timeout_ms=0) # no wakeup if we add that feature
 :      File "/opt/ns/python-apps/agent/app-env/lib/python3.7/site-packages/kafka/client_async.py", line 598, in poll
 :        self._poll(timeout / 1000)
 :      File "/opt/ns/python-apps/agent/app-env/lib/python3.7/site-packages/kafka/client_async.py", line 698, in _poll
 :        conn.config['request_timeout_ms']))
 :      File "/opt/ns/python-apps/agent/app-env/lib/python3.7/site-packages/kafka/conn.py", line 887, in close
 :        future.failure(error)
 :      File "/opt/ns/python-apps/agent/app-env/lib/python3.7/site-packages/kafka/future.py", line 45, in failure
 :        self._call_backs('errback', self._errbacks, self.exception)
 :      File "/opt/ns/python-apps/agent/app-env/lib/python3.7/site-packages/kafka/future.py", line 79, in _call_backs
 :        f(value)
 :      File "/opt/ns/python-apps/agent/app-env/lib/python3.7/site-packages/kafka/coordinator/base.py", line 499, in _failed_request
 :        future.failure(error)
 :      File "/opt/ns/python-apps/agent/app-env/lib/python3.7/site-packages/kafka/future.py", line 45, in failure
 :        self._call_backs('errback', self._errbacks, self.exception)
 :      File "/opt/ns/python-apps/agent/app-env/lib/python3.7/site-packages/kafka/future.py", line 79, in _call_backs
 :        f(value)
 :      File "/opt/ns/python-apps/agent/app-env/lib/python3.7/site-packages/kafka/coordinator/base.py", line 1006, in _handle_heartbeat_failure
 :        with self.coordinator._lock:
 :      File "/usr/lib/python3.7/threading.py", line 241, in __enter__
 :        return self._lock.__enter__()
 :      File "/usr/lib/python3.7/threading.py", line 148, in acquire
 :        rc = self._block.acquire(blocking, timeout)
 :      File "/opt/ns/python-apps/agent/app-env/lib/python3.7/site-packages/gevent/thread.py", line 118, in acquire
 :        acquired = BoundedSemaphore.acquire(self, blocking, timeout)
 :    Greenlet Locals:
 :      Local <class 'gevent.contextvars._ContextState'> at 0x7f99922b89d0
 :        {'context': <gevent.contextvars.Context object at 0x7f9991be4390>}
 +--- <Greenlet "Greenlet-0" at 0x7f998febba70: <bound method GitExecTimeCheck.long_running_git_check of <class 'agent.pkg.misc.nscfgsvclib.git_exec_time_check.GitExecTimeCheck'>>>
 :          Parent: <Hub '' at 0x7f999011a7d0 epoll default pending=0 ref=8 fileno=4 resolver=<gevent.resolver.thread.Resolver at 0x7f9993362990 pool=<ThreadPool at 0x7f9992bddad0 tasks=0 size=1 maxsize=10 hub=<Hub at 0x7f999011a7d0 thread_ident=0x7f99974e1700>>> threadpool=<ThreadPool at 0x7f9992bddad0 tasks=0 size=1 maxsize=10 hub=<Hub at 0x7f999011a7d0 thread_ident=0x7f99974e1700>> thread_ident=0x7f99974e1700>
 :          Running:
 :            File "/opt/ns/python-apps/agent/app-env/lib/python3.7/site-packages/agent/pkg/misc/nscfgsvclib/git_exec_time_check.py", line 22, in long_running_git_check
 :              gevent.sleep(600)
 :            File "/opt/ns/python-apps/agent/app-env/lib/python3.7/site-packages/gevent/hub.py", line 163, in sleep
 :              hub.wait(t)
 :          Spawned at:
 :            File "/opt/ns/python-apps/agent/app-env/bin/agentv2.py", line 55, in <module>
 :              agent.run()
 :            File "/opt/ns/python-apps/agent/app-env/bin/agentv2.py", line 46, in run
 :              self.monitor.start(self.kafka_consumer)
 :            File "/opt/ns/python-apps/agent/app-env/lib/python3.7/site-packages/agent/pkg/utils/monitor.py", line 23, in start
 :              th1 = Greenlet(GitExecTimeCheck.long_running_git_check)
 +--- <Greenlet "Greenlet-1" at 0x7f9992b92170: <bound method Monitor.check_kafka_offset of <agent.pkg.utils.monitor.Monitor object at 0x7f998fec2f90>>(<agent.pkg.kafka_consumer.kafka_consumer.Kafk)>
 :          Parent: <Hub '' at 0x7f999011a7d0 epoll default pending=0 ref=8 fileno=4 resolver=<gevent.resolver.thread.Resolver at 0x7f9993362990 pool=<ThreadPool at 0x7f9992bddad0 tasks=0 size=1 maxsize=10 hub=<Hub at 0x7f999011a7d0 thread_ident=0x7f99974e1700>>> threadpool=<ThreadPool at 0x7f9992bddad0 tasks=0 size=1 maxsize=10 hub=<Hub at 0x7f999011a7d0 thread_ident=0x7f99974e1700>> thread_ident=0x7f99974e1700>
 :          Running:
 :            File "/opt/ns/python-apps/agent/app-env/lib/python3.7/site-packages/agent/pkg/utils/monitor.py", line 98, in check_kafka_offset
 :              print_greenlet_stacktrace()
 :            File "/opt/ns/python-apps/agent/app-env/lib/python3.7/site-packages/agent/pkg/utils/utils.py", line 26, in print_greenlet_stacktrace
 :              gevent.util.print_run_info(file=fd)
 :            File "/opt/ns/python-apps/agent/app-env/lib/python3.7/site-packages/gevent/util.py", line 99, in print_run_info
 :              limit=limit)
 :            File "/opt/ns/python-apps/agent/app-env/lib/python3.7/site-packages/gevent/util.py", line 153, in format_run_info
 :              _format_greenlet_info(lines, greenlet_stacks, limit)
 :            File "/opt/ns/python-apps/agent/app-env/lib/python3.7/site-packages/gevent/util.py", line 215, in _format_greenlet_info
 :              'running_stack_limit': limit,
 :            File "/opt/ns/python-apps/agent/app-env/lib/python3.7/site-packages/gevent/util.py", line 362, in format_lines
 :              for l in self._render(tree)]
 :            File "/opt/ns/python-apps/agent/app-env/lib/python3.7/site-packages/gevent/util.py", line 435, in _render
 :              self.__render_children(tree)
 :            File "/opt/ns/python-apps/agent/app-env/lib/python3.7/site-packages/gevent/util.py", line 455, in __render_children
 :              child_tree = child._render(tree.deeper())
 :            File "/opt/ns/python-apps/agent/app-env/lib/python3.7/site-packages/gevent/util.py", line 419, in _render
 :              tree.details['running_stack_limit'])
 :            File "/opt/ns/python-apps/agent/app-env/lib/python3.7/site-packages/gevent/util.py", line 378, in __render_tb
 :              tb = ''.join(traceback.format_stack(frame, limit))
 :          Spawned at:
 :            File "/opt/ns/python-apps/agent/app-env/bin/agentv2.py", line 55, in <module>
 :              agent.run()
 :            File "/opt/ns/python-apps/agent/app-env/bin/agentv2.py", line 46, in run
 :              self.monitor.start(self.kafka_consumer)
 :            File "/opt/ns/python-apps/agent/app-env/lib/python3.7/site-packages/agent/pkg/utils/monitor.py", line 28, in start
 :              th2 = Greenlet(self.check_kafka_offset, kafka_consumer)
 +--- <Hub '' at 0x7f999011a7d0 epoll default pending=0 ref=8 fileno=4 resolver=<gevent.resolver.thread.Resolver at 0x7f9993362990 pool=<ThreadPool at 0x7f9992bddad0 tasks=0 size=1 maxsize=10 hub=<Hub at 0x7f999011a7d0 thread_ident=0x7f99974e1700>>> threadpool=<ThreadPool at 0x7f9992bddad0 tasks=0 size=1 maxsize=10 hub=<Hub at 0x7f999011a7d0 thread_ident=0x7f99974e1700>> thread_ident=0x7f99974e1700>
 :          Parent: <greenlet.greenlet object at 0x7f9994e7b310>
 :          Running:
 :            File "/opt/ns/python-apps/agent/app-env/lib/python3.7/site-packages/gevent/hub.py", line 639, in run
 :              loop.run()
 +--- <Greenlet "Greenlet-2" at 0x7f9992b923b0: <bound method Thread._bootstrap of <HeartbeatThread(agent_nsproxy1-1.bue1.nskope.net_AR-BUE1-heartbeat, started daemon 140297568330672)>>>
            Parent: <Hub '' at 0x7f999011a7d0 epoll default pending=0 ref=8 fileno=4 resolver=<gevent.resolver.thread.Resolver at 0x7f9993362990 pool=<ThreadPool at 0x7f9992bddad0 tasks=0 size=1 maxsize=10 hub=<Hub at 0x7f999011a7d0 thread_ident=0x7f99974e1700>>> threadpool=<ThreadPool at 0x7f9992bddad0 tasks=0 size=1 maxsize=10 hub=<Hub at 0x7f999011a7d0 thread_ident=0x7f99974e1700>> thread_ident=0x7f99974e1700>
            Running:
              File "/usr/lib/python3.7/threading.py", line 890, in _bootstrap
                self._bootstrap_inner()
              File "/usr/lib/python3.7/threading.py", line 926, in _bootstrap_inner
                self.run()
              File "/opt/ns/python-apps/agent/app-env/lib/python3.7/site-packages/kafka/coordinator/base.py", line 933, in run
                self._run_once()
              File "/opt/ns/python-apps/agent/app-env/lib/python3.7/site-packages/kafka/coordinator/base.py", line 965, in _run_once
                self.coordinator._client.poll(timeout_ms=0)
              File "/opt/ns/python-apps/agent/app-env/lib/python3.7/site-packages/kafka/client_async.py", line 572, in poll
                with self._lock:
              File "/usr/lib/python3.7/threading.py", line 148, in acquire
                rc = self._block.acquire(blocking, timeout)
              File "/opt/ns/python-apps/agent/app-env/lib/python3.7/site-packages/gevent/thread.py", line 118, in acquire
                acquired = BoundedSemaphore.acquire(self, blocking, timeout)
            Spawned at:
              File "/opt/ns/python-apps/agent/app-env/lib/python3.7/site-packages/agent/pkg/kafka_consumer/kafka_consumer.py", line 41, in run
                self._retrieve_message_with_retry()
              File "/opt/ns/python-apps/agent/app-env/lib/python3.7/site-packages/agent/pkg/kafka_consumer/kafka_consumer.py", line 116, in _retrieve_message_with_retry
                messages = self._consumer.poll(timeout_ms=1000)
              File "/opt/ns/python-apps/agent/app-env/lib/python3.7/site-packages/agent/pkg/misc/kafkawrapper/consumer.py", line 369, in poll
                topic_partitions_messages = self._consumer.poll(**kwargs)
              File "/opt/ns/python-apps/agent/app-env/lib/python3.7/site-packages/kafka/consumer/group.py", line 645, in poll
                records = self._poll_once(remaining, max_records, update_offsets=update_offsets)
              File "/opt/ns/python-apps/agent/app-env/lib/python3.7/site-packages/kafka/consumer/group.py", line 665, in _poll_once
                self._coordinator.poll()
              File "/opt/ns/python-apps/agent/app-env/lib/python3.7/site-packages/kafka/coordinator/consumer.py", line 286, in poll
                self.ensure_active_group()
              File "/opt/ns/python-apps/agent/app-env/lib/python3.7/site-packages/kafka/coordinator/base.py", line 351, in ensure_active_group
                self._start_heartbeat_thread()
              File "/opt/ns/python-apps/agent/app-env/lib/python3.7/site-packages/kafka/coordinator/base.py", line 742, in _start_heartbeat_thread
                self._heartbeat_thread.start()
              File "/usr/lib/python3.7/threading.py", line 852, in start
                _start_new_thread(self._bootstrap, ())
              File "/opt/ns/python-apps/agent/app-env/lib/python3.7/site-packages/gevent/thread.py", line 81, in start_new_thread
                greenlet = Greenlet.spawn(function, *args)
---- Thread boundary
<ThreadPoolWorker at 0x7f9992ba2730 thread_ident=0x7f998fb37700 threadpool-hub=<Hub at 0x7f999011a7d0 thread_ident=0x7f99974e1700>>
 :    Parent: <greenlet.greenlet object at 0x7f9992ba27e0>
```

**Comment by jeffwidman** [comment] 2020-07-11 05:23
This is a dupe of https://github.com/dpkp/kafka-python/issues/1985. See there for potential ways to solve. We are open to PR's fixing this.

**Closed by jeffwidman** 2020-07-11 05:23 UTC
