### ISSUE TITLE
Long delay before sending join group request

### ISSUE THREAD

**Issue by istaheev** [dpkp/kafka-python#1487] opened 2018-05-07 10:33 UTC
Sometimes when I am trying to consume messages using consumer groups the client waits for exactly 5 minutes before sending join group request so the script has effective delay of 5 minutes before starting doing some useful job. Such behavior appears randomly, sometimes it waits, sometimes not without any clear reasons. I played with different parameters like `max_poll_interval_ms` but it looks like they have no impact on this. I suspect this is somehow related to SASL_SSL connection.

`kafka-python` version: 1.4.2

Here is the minimal script:
```python
from __future__ import division, print_function

import logging
import six
import socket

from kafka import KafkaConsumer


logging.basicConfig(level=logging.DEBUG)

kafka_consumer = KafkaConsumer(
    bootstrap_servers=['kafka.hidden.com:9092'],
    group_id='my-consumer-group',
    client_id=socket.gethostname(),

    max_poll_records=10,
    enable_auto_commit=False,

    security_protocol='SASL_SSL',
    sasl_mechanism='PLAIN',
    sasl_plain_username='my-kafka-user',
    sasl_plain_password='foobar',
    ssl_check_hostname=False,
    ssl_cafile='kafka-ca.pem',
    ssl_certfile='kafka-cert.pem',
    ssl_keyfile='kafka-cert-key.pem',
)

kafka_consumer.subscribe(
    ['my-kafka-topic'],
)

while True:
    logging.info("Polling")
    kafka_messages = kafka_consumer.poll()
    logging.info("Polled: {} partitions".format(len(kafka_messages)))
    if not kafka_messages:
        continue

    for partition, records in six.iteritems(kafka_messages):
        logging.info("{}: {} messages".format(partition, len(records)))
```

Here is the output (lines beginning by "IS" are inserted by me to understand what's going on):

[Log](https://gist.github.com/istaheev/271083df3cf3123376e26d2560305943)

**Comment by bdvll** [comment] 2018-12-04 15:07
Also experiencing this issue. Did anyone find the reason for this?

**Comment by dpkp** [comment] 2019-03-08 06:49
Possibly related to #981 ...

**Comment by dpkp** [comment] 2019-03-08 16:06
I've merged some changes to master that I believe should address the underlying issue. Would love real-world feedback if you are able to test w/ the master branch!

**Comment by jeffwidman** [comment] 2019-03-13 15:47
I'm going to close this for now as I assume its fixed on master, happy to re-open if this is still a problem.

**Closed by jeffwidman** 2019-03-13 15:47 UTC

**Comment by arerlend** [comment] 2019-06-05 16:34
@jeffwidman @dpkp - I believe I'm seeing this when running against Event Hubs.  Looks like it might be a regression from 1.4.4 to 1.4.6 since the older version doesn't seem to present the hanging symptom.

I can send over client and service logs for both 1.4.4 and 1.4.6, but I've copied relevant snippets below for only the 1.4.6 version.

1.4.6 consistently displays the following behavior:
```
Starting new heartbeat thread
Revoking previously assigned partitions set([]) for group LYBIC
Initiating connection to node 0 at sbtest.servicebus.onebox.windows-int.net:9093
Added sensor with name node-0.bytes-sent
Added sensor with name node-0.bytes-received
Added sensor with name node-0.latency
<BrokerConnection node_id=0 host=sbtest.servicebus.onebox.windows-int.net:9093 <disconnected> [unspecified None]>: creating new socket
<BrokerConnection node_id=0 host=sbtest.servicebus.onebox.windows-int.net:9093 <disconnected> [IPv4 ('10.91.40.96', 9093)]>: setting socket option (6, 1, 1)
<BrokerConnection node_id=0 host=sbtest.servicebus.onebox.windows-int.net:9093 <connecting> [IPv4 ('10.91.40.96', 9093)]>: connecting to sbtest.servicebus.onebox.windows-int.net:9093 [('10.91.40.96', 9093) IPv4]
Heartbeat thread started
<BrokerConnection node_id=0 host=sbtest.servicebus.onebox.windows-int.net:9093 <connecting> [IPv4 ('10.91.40.96', 9093)]>: established TCP connection
<BrokerConnection node_id=0 host=sbtest.servicebus.onebox.windows-int.net:9093 <connecting> [IPv4 ('10.91.40.96', 9093)]>: initiating SSL handshake
<BrokerConnection node_id=0 host=sbtest.servicebus.onebox.windows-int.net:9093 <handshake> [IPv4 ('10.91.40.96', 9093)]>: configuring default SSL Context
<BrokerConnection node_id=0 host=sbtest.servicebus.onebox.windows-int.net:9093 <handshake> [IPv4 ('10.91.40.96', 9093)]>: Loading SSL CA from /usr/lib/ssl/certs/ca-certificates.crt
<BrokerConnection node_id=0 host=sbtest.servicebus.onebox.windows-int.net:9093 <handshake> [IPv4 ('10.91.40.96', 9093)]>: wrapping socket in ssl context
<BrokerConnection node_id=0 host=sbtest.servicebus.onebox.windows-int.net:9093 <handshake> [IPv4 ('10.91.40.96', 9093)]>: completed SSL handshake.
<BrokerConnection node_id=0 host=sbtest.servicebus.onebox.windows-int.net:9093 <handshake> [IPv4 ('10.91.40.96', 9093)]>: initiating SASL authentication
Sending request SaslHandShakeRequest_v0(mechanism='PLAIN')
<BrokerConnection node_id=0 host=sbtest.servicebus.onebox.windows-int.net:9093 <authenticating> [IPv4 ('10.91.40.96', 9093)]> Request 1: SaslHandShakeRequest_v0(mechanism='PLAIN')
Received correlation id: 1
Processing response SaslHandShakeResponse_v0
<BrokerConnection node_id=0 host=sbtest.servicebus.onebox.windows-int.net:9093 <authenticating> [IPv4 ('10.91.40.96', 9093)]> Response 1 (100.979804993 ms): SaslHandShakeResponse_v0(error_code=0, enabled_mechanisms=[u'PLAIN'])
<BrokerConnection node_id=0 host=sbtest.servicebus.onebox.windows-int.net:9093 <authenticating> [IPv4 ('10.91.40.96', 9093)]>: Authenticated as $ConnectionString via PLAIN
<BrokerConnection node_id=0 host=sbtest.servicebus.onebox.windows-int.net:9093 <authenticating> [IPv4 ('10.91.40.96', 9093)]>: Connection complete.
Node 0 connected
<BrokerConnection node_id=bootstrap-0 host=sbtest.servicebus.onebox.windows-int.net:9093 <connected> [IPv4 ('10.91.40.96', 9093)]>: Closing connection. 
<BrokerConnection node_id=bootstrap-0 host=sbtest.servicebus.onebox.windows-int.net:9093 <connected> [IPv4 ('10.91.40.96', 9093)]>: reconnect backoff 0.0467664959975 after 1 failures
***********    HANGS HERE     ***********
Sending metadata request MetadataRequest_v1(topics=['bqcm']) to node 0
Sending request MetadataRequest_v1(topics=['bqcm'])
<BrokerConnection node_id=0 host=sbtest.servicebus.onebox.windows-int.net:9093 <connected> [IPv4 ('10.91.40.96', 9093)]> Request 3: MetadataRequest_v1(topics=['bqcm'])
Received correlation id: 3
Processing response MetadataResponse_v1
<BrokerConnection node_id=0 host=sbtest.servicebus.onebox.windows-int.net:9093 <connected> [IPv4 ('10.91.40.96', 9093)]> Response 3 (6.78706169128 ms): MetadataResponse_v1(brokers=[(node_id=0, host=u'sbtest.servicebus.onebox.windows-int.net', port=9093, rack=None)], controller_id=0, topics=[(error_code=0, topic=u'bqcm', is_internal=False, partitions=[(error_code=0, partition=0, leader=0, replicas=[], isr=[]), (error_code=0, partition=1, leader=0, replicas=[], isr=[])])])
Updated cluster metadata to ClusterMetadata(brokers: 1, topics: 1, groups: 0)
(Re-)joining group LYBIC
Sending JoinGroup (JoinGroupRequest_v2(group='LYBIC', session_timeout=10000, rebalance_timeout=300000, member_id='', protocol_type='consumer', group_protocols=[(protocol_name='range', protocol_metadata='\x00\x00\x00\x00\x00\x01\x00\x04bqcm\x00\x00\x00\x00'), (protocol_name='roundrobin', protocol_metadata='\x00\x00\x00\x00\x00\x01\x00\x04bqcm\x00\x00\x00\x00')])) to coordinator 0
Sending request JoinGroupRequest_v2(group='LYBIC', session_timeout=10000, rebalance_timeout=300000, member_id='', protocol_type='consumer', group_protocols=[(protocol_name='range', protocol_metadata='\x00\x00\x00\x00\x00\x01\x00\x04bqcm\x00\x00\x00\x00'), (protocol_name='roundrobin', protocol_metadata='\x00\x00\x00\x00\x00\x01\x00\x04bqcm\x00\x00\x00\x00')])
```

Service logs with timestamps:
```
17:35:43.907 RECV kafka-python-1.4.6 {ApiKey:17,ApiVersion:0,CorrelationId:1,ClientId:kafka-python-1.4.6}{Mechanism:PLAIN}
17:35:43.908 SEND kafka-python-1.4.6 {CorrelationId:1,ErrorCode:0,EnabledMechanisms:[PLAIN]}
17:35:44.009 RECV kafka-python-1.4.6 {ApiKey:3,ApiVersion:1,CorrelationId:2,ClientId:kafka-python-1.4.6}{Topics:[bqcm]}
17:35:44.010 SEND kafka-python-1.4.6 {CorrelationId:2,Brokers:[{NodeId:0,Host:sbtest.servicebus.onebox.windows-int.net,Port:9093,Rack:}],ControllerId:0,Topics:[{ErrorCode:0,Topic:bqcm,IsInternal:False,Partitions:[{ErrorCode:0,Partition:0,Leader:0,Replicas:[],ISR:[]},{ErrorCode:0,Partition:1,Leader:0,Replicas:[],ISR:[]}]}]}
17:35:44.110 RECV kafka-python-1.4.6 {ApiKey:10,ApiVersion:0,CorrelationId:3,ClientId:kafka-python-1.4.6}{GroupId:LYBIC}
17:35:44.110 SEND kafka-python-1.4.6 {CorrelationId:3,ErrorCode:0,Coordinator:{NodeId:0,Host:sbtest.servicebus.onebox.windows-int.net,Port:9093}}
17:35:44.426 RECV kafka-python-1.4.6 {ApiKey:17,ApiVersion:0,CorrelationId:1,ClientId:kafka-python-1.4.6}{Mechanism:PLAIN}
17:35:44.426 SEND kafka-python-1.4.6 {CorrelationId:1,ErrorCode:0,EnabledMechanisms:[PLAIN]}
17:40:44.202 RECV kafka-python-1.4.6 {ApiKey:11,ApiVersion:2,CorrelationId:2,ClientId:kafka-python-1.4.6}{GroupId:LYBIC,SessionTimeout:10000,RebalanceTimeout:300000,MemberId:,ProtocolType:consumer,Protocols:[{Name:range,Metadata:0000000000010004...(8)},{Name:roundrobin,Metadata:0000000000010004...(8)}]}
17:40:44.226 RECV kafka-python-1.4.6 {ApiKey:3,ApiVersion:1,CorrelationId:3,ClientId:kafka-python-1.4.6}{Topics:[bqcm]}
17:40:44.732 SEND kafka-python-1.4.6 {CorrelationId:2,ThrottleTimeMs:0,ErrorCode:0,GenerationId:1,GroupProtocol:range,Leader:sbtest.servicebus.onebox.windows-int.net:c:lybic:I:kafka-python-1.4.6-050582d895cc45a6b01a379048a41d59,MemberId:sbtest.servicebus.onebox.windows-int.net:c:lybic:I:kafka-python-1.4.6-050582d895cc45a6b01a379048a41d59,Members:[{Id:sbtest.servicebus.onebox.windows-int.net:c:lybic:I:kafka-python-1.4.6-050582d895cc45a6b01a379048a41d59,Metadata:0000000000010004...(8)}]}
17:40:44.733 SEND kafka-python-1.4.6 {CorrelationId:3,Brokers:[{NodeId:0,Host:sbtest.servicebus.onebox.windows-int.net,Port:9093,Rack:}],ControllerId:0,Topics:[{ErrorCode:0,Topic:bqcm,IsInternal:False,Partitions:[{ErrorCode:0,Partition:0,Leader:0,Replicas:[],ISR:[]},{ErrorCode:0,Partition:1,Leader:0,Replicas:[],ISR:[]}]}]}
17:40:44.737 RECV kafka-python-1.4.6 {ApiKey:14,ApiVersion:1,CorrelationId:4,ClientId:kafka-python-1.4.6}{GroupId:LYBIC,GenerationId:1,MemberId:sbtest.servicebus.onebox.windows-int.net:c:lybic:I:kafka-python-1.4.6-050582d895cc45a6b01a379048a41d59,Assignments:[{MemberId:sbtest.servicebus.onebox.windows-int.net:c:lybic:I:kafka-python-1.4.6-050582d895cc45a6b01a379048a41d59,Assignment:0000000000010004...(20)}]}
17:40:44.757 SEND kafka-python-1.4.6 {CorrelationId:4,ThrottleTimeMs:0,ErrorCode:0,Assignment:0000000000010004...(20)}
```

I haven't been able to set up a real Kafka broker with SASL_SSL PLAIN auth - was hoping you guys had a better way to test this out.

**Comment by arerlend** [comment] 2019-06-05 16:38
It's a bit unclear to me why the connection is getting closed and failed before hanging, no SSL failures on the Event Hubs side.

I don't see the same pattern of a successful connection then close for 1.4.4 client logs - 

```
Starting new heartbeat thread
Revoking previously assigned partitions set([]) for group KADUN
Heartbeat thread started
Received correlation id: 3
Processing response MetadataResponse_v1
<BrokerConnection node_id=0 host=sbtest.servicebus.onebox.windows-int.net:9093 <connected> [IPv4 ('10.91.40.96', 9093)]> Response 3 (28.5329818726 ms): MetadataResponse_v1(brokers=[(node_id=0, host=u'sbtest.servicebus.onebox.windows-int.net', port=9093, rack=None)], controller_id=0, topics=[(error_code=0, topic=u'abcdef', is_internal=False, partitions=[(error_code=0, partition=0, leader=0, replicas=[], isr=[]), (error_code=0, partition=1, leader=0, replicas=[], isr=[])])])
Updated cluster metadata to ClusterMetadata(brokers: 1, topics: 1, groups: 1)
(Re-)joining group KADUN
Sending JoinGroup (JoinGroupRequest_v2(group='KADUN', session_timeout=10000, rebalance_timeout=300000, member_id='', protocol_type='consumer', group_protocols=[(protocol_name='range', protocol_metadata='\x00\x00\x00\x00\x00\x01\x00\x06abcdef\x00\x00\x00\x00'), (protocol_name='roundrobin', protocol_metadata='\x00\x00\x00\x00\x00\x01\x00\x06abcdef\x00\x00\x00\x00')])) to coordinator 0
Sending request JoinGroupRequest_v2(group='KADUN', session_timeout=10000, rebalance_timeout=300000, member_id='', protocol_type='consumer', group_protocols=[(protocol_name='range', protocol_metadata='\x00\x00\x00\x00\x00\x01\x00\x06abcdef\x00\x00\x00\x00'), (protocol_name='roundrobin', protocol_metadata='\x00\x00\x00\x00\x00\x01\x00\x06abcdef\x00\x00\x00\x00')])
<BrokerConnection node_id=0 host=sbtest.servicebus.onebox.windows-int.net:9093 <connected> [IPv4 ('10.91.40.96', 9093)]> Request 4: JoinGroupRequest_v2(group='KADUN', session_timeout=10000, rebalance_timeout=300000, member_id='', protocol_type='consumer', group_protocols=[(protocol_name='range', protocol_metadata='\x00\x00\x00\x00\x00\x01\x00\x06abcdef\x00\x00\x00\x00'), (protocol_name='roundrobin', protocol_metadata='\x00\x00\x00\x00\x00\x01\x00\x06abcdef\x00\x00\x00\x00')])
```
