### ISSUE TITLE
Reconnection to broker

### ISSUE THREAD

**Issue by deepsrm** [dpkp/kafka-python#530] opened 2016-02-01 15:15 UTC
Hi!

With the latest version (0.97.0.dev0) the client is not doing the auto reconnect after the timeout error nor raising an error (using the new KafkaProducer class with the default params). When the broker is down for a while, lets say 10-30s it is doing it well, but not in the case that for example 1h down.

Any suggestions, ideas?

Thank you!

**Comment by dpkp** [comment] 2016-02-01 15:53
Are you using KafkaConsumer or KafkaProducer? Can you post a code snippet?

**Comment by deepsrm** [comment] 2016-02-01 16:11
I'm using KafkaProducer,

Omitting the non relevant code:
```
self.kafka_producer = KafkaProducer(bootstrap_servers=['localhost:9092], acks = 0, value_serializer=lambda m: json.dumps(m).encode('ascii'), retries = 0)

#for sending to the broker (async):
while True:
    self.kafka_producer.send(self.KAFKA_TOPIC, {'bar':'foo'})
    sleep(1)

```

**Comment by dpkp** [comment] 2016-02-01 17:47
Thanks -- what is your cluster configuration? Nodes / partitions-per-topic / replication_factor ? I'll spin up a test cluster and try to reproduce.

**Comment by dpkp** [comment] 2016-02-01 17:49
also, broker version? 0.9.0.0 ?

Note that when a broker goes down, the partitions it was leading should get transferred to an in-sync replica. Can you verify from the server logs whether that is happening correctly?

**Comment by deepsrm** [comment] 2016-02-01 18:12
Thanks for the quick response, the broker version is the latest stable 0.8.2.2
The python version is 2.7.6

My testing environment is just with the default config, 1 partition per topic, 1 node, 1 replica.

Server system logs when turning the broker down:

```
WARN [ConsumerFetcherThread-console-consumer-59045_controller-1454347538549-a4e6b165-0-0], Error in fetch Name: FetchRequest; Version: 0; CorrelationId: 1; ClientId: console-consumer-59045; ReplicaId: -1; MaxWait: 100 ms; MinBytes: 1 bytes; RequestInfo: [TutorialTopic,0] -> PartitionFetchInfo(6919,1048576). Possible cause: java.nio.channels.ClosedChannelException (kafka.consumer.ConsumerFetcherThread)
[2016-02-01 17:25:39,959] WARN Fetching topic metadata with correlation id 1 for topics [Set(TutorialTopic)] from broker [id:0,host:controller,port:9092] failed (kafka.client.ClientUtils$)
java.nio.channels.ClosedChannelException
	at kafka.network.BlockingChannel.send(BlockingChannel.scala:100)
	at kafka.producer.SyncProducer.liftedTree1$1(SyncProducer.scala:73)
	at kafka.producer.SyncProducer.kafka$producer$SyncProducer$$doSend(SyncProducer.scala:72)
	at kafka.producer.SyncProducer.send(SyncProducer.scala:113)
	at kafka.client.ClientUtils$.fetchTopicMetadata(ClientUtils.scala:58)
	at kafka.client.ClientUtils$.fetchTopicMetadata(ClientUtils.scala:93)
	at kafka.consumer.ConsumerFetcherManager$LeaderFinderThread.doWork(ConsumerFetcherManager.scala:66)
	at kafka.utils.ShutdownableThread.run(ShutdownableThread.scala:60)

	[2016-02-01 17:25:39,965] WARN [console-consumer-59045_controller-1454347538549-a4e6b165-leader-finder-thread], Failed to find leader for Set([TutorialTopic,0]) (kafka.consumer.ConsumerFetcherManager$LeaderFinderThread)
kafka.common.KafkaException: fetching topic metadata for topics [Set(TutorialTopic)] from broker [ArrayBuffer(id:0,host:controller,port:9092)] failed
	at kafka.client.ClientUtils$.fetchTopicMetadata(ClientUtils.scala:72)
	at kafka.client.ClientUtils$.fetchTopicMetadata(ClientUtils.scala:93)
	at kafka.consumer.ConsumerFetcherManager$LeaderFinderThread.doWork(ConsumerFetcherManager.scala:66)
	at kafka.utils.ShutdownableThread.run(ShutdownableThread.scala:60)
Caused by: java.nio.channels.ClosedChannelException
	at kafka.network.BlockingChannel.send(BlockingChannel.scala:100)
	at kafka.producer.SyncProducer.liftedTree1$1(SyncProducer.scala:73)
	at kafka.producer.SyncProducer.kafka$producer$SyncProducer$$doSend(SyncProducer.scala:72)
	at kafka.producer.SyncProducer.send(SyncProducer.scala:113)
	at kafka.client.ClientUtils$.fetchTopicMetadata(ClientUtils.scala:58)
	... 3 more
[2016-02-01 17:25:40,218] WARN Fetching topic metadata with correlation id 2 for topics [Set(TutorialTopic)] from broker [id:0,host:controller,port:9092] failed (kafka.client.ClientUtils$)
java.nio.channels.ClosedChannelException
	at kafka.network.BlockingChannel.send(BlockingChannel.scala:100)
	at kafka.producer.SyncProducer.liftedTree1$1(SyncProducer.scala:73)
	at kafka.producer.SyncProducer.kafka$producer$SyncProducer$$doSend(SyncProducer.scala:72)
	at kafka.producer.SyncProducer.send(SyncProducer.scala:113)
	at kafka.client.ClientUtils$.fetchTopicMetadata(ClientUtils.scala:58)
	at kafka.client.ClientUtils$.fetchTopicMetadata(ClientUtils.scala:93)
	at kafka.consumer.ConsumerFetcherManager$LeaderFinderThread.doWork(ConsumerFetcherManager.scala:66)
	at kafka.utils.ShutdownableThread.run(ShutdownableThread.scala:60)
[2016-02-01 17:25:40,229] WARN [console-consumer-59045-controller-1454347538549-a4e6b165-leader-finder-thread], Failed to find leader for Set([TutorialTopic,0]) (kafka.consumer.ConsumerFetcherManager$LeaderFinderThread)
kafka.common.KafkaException: fetching topic metadata for topics [Set(TutorialTopic)] from broker [ArrayBuffer(id:0,host:controller,port:9092)] failed
	at kafka.client.ClientUtils$.fetchTopicMetadata(ClientUtils.scala:72)
	at kafka.client.ClientUtils$.fetchTopicMetadata(ClientUtils.scala:93)
	at kafka.consumer.ConsumerFetcherManager$LeaderFinderThread.doWork(ConsumerFetcherManager.scala:66)
	at kafka.utils.ShutdownableThread.run(ShutdownableThread.scala:60)
Caused by: java.nio.channels.ClosedChannelException
	at kafka.network.BlockingChannel.send(BlockingChannel.scala:100)
	at kafka.producer.SyncProducer.liftedTree1$1(SyncProducer.scala:73)
	at kafka.producer.SyncProducer.kafka$producer$SyncProducer$$doSend(SyncProducer.scala:72)
	at kafka.producer.SyncProducer.send(SyncProducer.scala:113)
	at kafka.client.ClientUtils$.fetchTopicMetadata(ClientUtils.scala:58)
	... 3 more
```

**Comment by dpkp** [comment] 2016-02-02 15:59
I'm unable to reproduce. How long are you waiting for recovery? If you kill the entire cluster so that there are no known brokers alive, the client will exponentially backoff up to a max delay of about 3.5 minutes.

**Comment by deepsrm** [comment] 2016-02-02 16:41
As I said, after a short period, 20-30s after starting the broker, the client auto reconnects, but after for example 30min It doesn't reconnect again. I waited like 1h for recovery and nothing happened. Are you able to reconnect after that period? is there any way to check if the client is connected, so i can force it to came up again?

**Comment by dpkp** [comment] 2016-02-02 19:41
Can you enable debug logging and track the status of your producer as broker fails / recovers? The internal client is local to the background thread, but it should continually attempt to reconnect / rebootstrap on failures (subject to exponential backoff).

I'm not able to reproduce. The client is managed by the background sender thread and is not threadsafe to access directly from the producer object. Nonetheless, you can get it via `producer._sender._client`. Like I said, the sender thread reconnects in all of my tests (tested on both 0.9 and 0.8.2.2 brokers, with 1 broker and 2).

**Comment by deepsrm** [comment] 2016-02-02 21:11
After some tests done with the DEBUG mode, here you have the error I got, this error happens continuously. It tries to reconnect, and it does when the time with the broker down is not too long, after that i got the following:

```
DEBUG:kafka.producer.kafka:Waking up the sender since TopicPartition(topic='TutorialTopic', partition=0) is either full or getting a new batch
.
.
.
#the above log is repeated and the backoff retry seems to work

AssertionError: Future is already complete
DEBUG:kafka.producer.record_accumulator:Produced messages to topic-partition TopicPartition(topic='TutorialTopic', partition=0) with base offset -1 and error Batch Expired.
ERROR:kafka.producer.sender:Uncaught error in kafka producer I/O thread
Traceback (most recent call last):
  File "build/bdist.linux-x86_64/egg/kafka/producer/sender.py", line 58, in run
    self.run_once()
  File "build/bdist.linux-x86_64/egg/kafka/producer/sender.py", line 116, in run_once
    self.config['request_timeout_ms'], self._metadata)
  File "build/bdist.linux-x86_64/egg/kafka/producer/record_accumulator.py", line 255, in abort_expired_batches
    self.config['linger_ms']):
  File "build/bdist.linux-x86_64/egg/kafka/producer/record_accumulator.py", line 81, in maybe_expire
    self.done(-1, Errors.KafkaTimeoutError('Batch Expired'))
  File "build/bdist.linux-x86_64/egg/kafka/producer/record_accumulator.py", line 74, in done
    self.produce_future.failure(exception)
  File "build/bdist.linux-x86_64/egg/kafka/producer/future.py", line 23, in failure
    ret = super(FutureProduceResult, self).failure(error)
  File "build/bdist.linux-x86_64/egg/kafka/future.py", line 41, in failure
    assert not self.is_done, 'Future is already complete'
```

**Comment by dpkp** [comment] 2016-02-02 23:18
Thanks. The first message is normal. I just pushed a fix for the uncaught
error. Can you pull master and try again?

**Comment by deepsrm** [comment] 2016-02-02 23:54
It seems fixed after your commit! anyway if I will do further testing during the following days and came back here if necessary. 
Thank you!

**Comment by dpkp** [comment] 2016-02-03 00:19
no problem - thanks for the great bug report and sticking with me while I tried to reproduce!

**Closed by dpkp** 2016-02-03 00:19 UTC

**Comment by mario-bros** [comment] 2024-01-24 10:16
> Thanks. The first message is normal. I just pushed a fix for the uncaught error. Can you pull master and try again?

Sorry , where is the commit hash of this fix ? thanks
