### ISSUE TITLE
kafka.common.KafkaTimeoutError: ('Failed to update metadata after %s secs.', 60.0)

### ISSUE THREAD

**Issue by archiechen** [dpkp/kafka-python#607] opened 2016-03-18 00:46 UTC
kafka version: 0.8.2.0-1.kafka1.3.2.p0.15 (cloudera released)

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/archimonde/lib/python2.6/site-packages/kafka/producer/kafka.py", line 357, in send
    self._wait_on_metadata(topic, self.config['max_block_ms'] / 1000.0)
  File "/opt/archimonde/lib/python2.6/site-packages/kafka/producer/kafka.py", line 465, in _wait_on_metadata
    "Failed to update metadata after %s secs.", max_wait)
kafka.common.KafkaTimeoutError: ('Failed to update metadata after %s secs.', 60.0)
```

But it's ok on 2.0.0-1.kafka2.0.0.p0.12.

**Comment by archiechen** [comment] 2016-03-18 01:40
resolved.

**Comment by khangnguyen** [comment] 2016-10-27 09:26
@archiechen I am getting the same error too, what did you do?

**Comment by jasonrhaas** [comment] 2016-12-14 09:42
so what is the fix here?

**Comment by nicholasserra** [comment] 2017-01-25 20:57
Also wondering fix. I see this error when running kafka via Docker but not when installing from binary.

**Comment by lukewendling** [comment] 2017-07-12 14:35
Anyone get an answer to this?

**Comment by softwarevamp** [comment] 2017-09-01 11:49
docker default bind to ipv6 only. but usually you may miss configuring listeners of ipv4.

**Comment by jeffwidman** [comment] 2017-12-02 02:35
I am re-opening, I also saw the same issue in production with `kafka-python` 1.3.5 and kafka broker 0.10.0.1. The producer was a VM, the broker was baremetal--no docker here.

The error showed up after rolling the kafka cluster, and the `KafkaProducer` instance never recovered, just continually threw this error once a minute.

I watched the tcpstream and the producer never tried to even talk to Kafka, so it wasn't timing out cluster side.

When I restarted the service, it immediately started working.

**Comment by geoff-va** [comment] 2018-01-10 19:38
I too saw this exact issue with `kafka-python` 1.3.5 and kafka broker 1.0.0. I tried restarting one of the brokers, and now I continually get the following message:

`kafka.errors.KafkaTimeoutError: KafkaTimeoutError: Failed to update metadata after 60.0 secs.`

My producer is running inside a docker container, but both kafka brokers are running in linux via supervisor. Both of my brokers are included via `bootstrap_servers`.

**Comment by griff122** [comment] 2018-02-13 18:51
Another cause for this issue is using a `bytes` object as the topic name, instead of a string. In python 3, you could have a string come in as a bytes object (`a = b'test_string'`). If this happens, you can just convert the topic name to a utf-8 string, and it might start working. It worked for me. 

```
if type(kafka_topic) == bytes:
    kafka_topic = kafka_topic.decode('utf-8')
kafka_producer = KafkaProducer(bootstrap_servers=kafka_brokers)
kafka_producer.send(kafka_topic, payload)
kafka_producer.flush()
```

**Comment by brennerm** [comment] 2018-02-20 10:21
Steps to reproduce the issue:

1. Clone Kafka Docker repo `git clone https://github.com/wurstmeister/kafka-docker`
2. Clone kafka-python repo `git clone https://github.com/dpkp/kafka-python`
3. Start Kafka `( cd kafka-docker; docker-compose up -d )`
4. Find out Kafka broker port `docker ps`
5. Set correct broker port in example.py `cd kafka-python; vi example.py` (line 17 and 35)
6. Execute example `python example.py`

**Comment by dustinfarris** [comment] 2018-02-23 21:41
here's the logs right before the timeout:

```
DEBUG 2018-02-24 05:38:58,420 kafka 46849 Requesting metadata update for topic ('example',)
DEBUG 2018-02-24 05:38:58,520 client_async 46849 Sending metadata request MetadataRequest_v1(topics=[('example',)]) to node 1011
DEBUG 2018-02-24 05:38:58,520 parser 46849 Sending request MetadataRequest_v1(topics=[('example',)])
DEBUG 2018-02-24 05:38:58,520 conn 46849 <BrokerConnection node_id=1011 host=localhost/::1 port=9092> Request 562: MetadataRequest_v1(topics=[('example',)])
DEBUG 2018-02-24 05:38:58,523 parser 46849 Received correlation id: 562
DEBUG 2018-02-24 05:38:58,523 parser 46849 Processing response MetadataResponse_v1
DEBUG 2018-02-24 05:38:58,523 conn 46849 <BrokerConnection node_id=1011 host=localhost/::1 port=9092> Response 562 (3.287076950073242 ms): MetadataResponse_v1(brokers=[(node_id=1011, host='localhost', port=9092, rack=None)], controller_id=1011, topics=[(error_code=17, topic="('example',)", is_internal=False, partitions=[])])
DEBUG 2018-02-24 05:38:58,523 kafka 46849 _wait_on_metadata woke after 59.96455192565918 secs.
DEBUG 2018-02-24 05:38:58,524 kafka 46849 Requesting metadata update for topic ('example',)
Traceback (most recent call last):
  File "/Users/dustin/.virtualenvs/oda-data-pipe/bin/oda", line 11, in <module>
    load_entry_point('oda-data-pipe', 'console_scripts', 'oda')()
  File "/Users/dustin/Work/cu/oda-data-pipe/oda_data_pipe/main.py", line 150, in main
    args.func(args)
  File "/Users/dustin/Work/cu/oda-data-pipe/oda_data_pipe/main.py", line 28, in produce
    job_module.extract()
  File "/Users/dustin/Work/cu/oda-data-pipe/oda_data_pipe/oda_producer.py", line 53, in wrapper
    kafka_producer.send(topic_name, item)
  File "/Users/dustin/.virtualenvs/oda-data-pipe/lib/python3.6/site-packages/kafka/producer/kafka.py", line 546, in send
    self._wait_on_metadata(topic, self.config['max_block_ms'] / 1000.0)
  File "/Users/dustin/.virtualenvs/oda-data-pipe/lib/python3.6/site-packages/kafka/producer/kafka.py", line 664, in _wait_on_metadata
    "Failed to update metadata after %.1f secs." % max_wait)
kafka.errors.KafkaTimeoutError: KafkaTimeoutError: Failed to update metadata after 60.0 secs.
INFO 2018-02-24 05:38:58,561 kafka 46849 Closing the Kafka producer with 0 secs timeout.
INFO 2018-02-24 05:38:58,561 kafka 46849 Proceeding to force close the producer since pending requests could not be completed within timeout 0.
DEBUG 2018-02-24 05:38:58,562 sender 46849 Beginning shutdown of Kafka producer I/O thread, sending remaining records.
INFO 2018-02-24 05:38:58,562 conn 46849 <BrokerConnection node_id=1011 host=localhost/::1 port=9092>: Closing connection.
DEBUG 2018-02-24 05:38:58,563 conn 46849 <BrokerConnection node_id=1011 host=localhost/::1 port=9092>: reconnect backoff 0.04849831291093153 after 1 failures
DEBUG 2018-02-24 05:38:58,563 sender 46849 Shutdown of Kafka producer I/O thread has completed.
DEBUG 2018-02-24 05:38:58,563 kafka 46849 The Kafka producer has closed.
INFO 2018-02-24 05:38:58,572 kafka 46849 Kafka producer closed
```

**Comment by dustinfarris** [comment] 2018-02-23 21:50
I've also noticed that using kafka-python in the interpreter works just fine, with the exact same bootstrap_servers and everything else.  The bug only surfaces when executed as part of a Python program.

**Comment by dpkp** [comment] 2018-03-09 22:35
If this happens before any message is able to be sent then it typically indicates a low-level connection error. Take a look at the kafka.conn.BrokerConnection debug logs. I've made several changes to the network connection code on master to handle various edge cases that you may be hitting. If you are able to test with master, can you check whether this issue is fixed now?

**Comment by benkibejs** [comment] 2018-03-19 14:08
I am having the same issue with 1.4.2 and 1.4.3-dev0. Do not understand where i can find the debug logs you are talking about. Would they be somewhere in the docker volume? 
`Traceback (most recent call last):
  File "producer.py", line 41, in <module>
    producer.send('answer_topic', value=message)
  File "/usr/local/lib/python3.5/dist-packages/kafka/producer/kafka.py", line 543, in send
    self._wait_on_metadata(topic, self.config['max_block_ms'] / 1000.0)
  File "/usr/local/lib/python3.5/dist-packages/kafka/producer/kafka.py", line 664, in _wait_on_metadata
    "Failed to update metadata after %.1f secs." % max_wait)
kafka.errors.KafkaTimeoutError: KafkaTimeoutError: Failed to update metadata after 60.0 secs.`

**Comment by dpkp** [comment] 2018-03-23 01:20
to enable python logging at its most simple form:
```
import logging
logging.basicConfig(level=logging.DEBUG)
```

**Comment by james-woods** [comment] 2018-04-16 08:14
I am having the same issue while using minikube and [https://github.com/Yolean/kubernetes-kafka](kubernetes-kafka) (Kubernetes version 1.9.0, Kafka 1.0)

**Comment by GagandeepS** [comment] 2018-06-11 17:03
Whats the fix for this issue guys?

**Comment by madss** [comment] 2018-07-05 13:09
If running the kafka brokers inside a container, make sure that it advertises the correct hostnames that are accessible by the clients. If not specified it will use the canonical hostname of the container and that may be an internal one that cannot be used outside of the container.

You can set the advertised hosts with `advertised.listeners` in the server properties, or if you just want to test with an unmodified kafka docker image, you can override the default setting with:
```
bin/kafka-server-start.sh config/server.properties --override advertised.listeners=PLAINTEXT://<accessible-hostname>:9092
```

**Comment by mikekeda** [comment] 2018-09-12 15:28
I had same problem,
To solve the problem I increased request_timeout_ms (I used 10ms before)

**Comment by egodigitus** [comment] 2018-09-14 06:34
Had the same issue.
Was producing against a kafka cluster which was not available, changing the cluster address to an available one fixed the problem for me

**Comment by worms** [comment] 2018-09-18 18:28
You will also see this if you disallow topic creation on publish on the broker (auto.create.topics.enable=false) and then try to produce to a topic that hasn't been created yet.

**Comment by chunzhenzyd** [comment] 2018-09-26 10:01
Hi,

How to fix this problem ?

**Comment by bolianlai** [comment] 2018-12-18 12:12
I have encountered this problem when I connect to kafka deployed with docker. How can I solve this problem?

**Comment by llevar** [comment] 2019-02-13 13:57
I got this message when trying to publish to a topic that doesn't exist.

**Comment by tvoinarovskyi** [comment] 2019-02-22 18:28
@jeffwidman 
Due to the essense of how Kubernetis uses DNS, maybe the root cause here is that we either cache dns records or that the Kubernetis setup does not broadcast DNS's in advertized.listeners, but IP addresses.
Most likely after rolling a new instance it still continued to use old IP.

**Comment by tvoinarovskyi** [comment] 2019-02-22 18:33
For others in thread, this error means that the client could not connect to a node. Most likely it's not visible. Please make sure the `advertized.listener` config is valid. For Kubenetes users, please make sure you adverize the same dns as you bootstrap from.

**Comment by jeffwidman** [comment] 2019-02-27 18:03
Right, but I saw it in a non-Kubernetes environment.

> I got this message when trying to publish to a topic that doesn't exist.

I haven't examined the actual code path, but it would be nice if we threw a more obvious error for that scenario.

**Comment by christian-quisbert** [comment] 2019-03-07 14:33
Hi, i have the same problem with kafka inside Docker. 
I leave the Exception log :

```
Service    | Exception in thread Thread-2:
Service    | Traceback (most recent call last):
Service    |   File "/usr/local/lib/python2.7/threading.py", line 801, in __bootstrap_inner
Service    |     self.run()
Service    |   File "/usr/local/lib/python2.7/threading.py", line 754, in run
Service    |     self.__target(*self.__args, **self.__kwargs)
Service    |   File "<file>.py", line XX, in worker
Service    |     self.producer.send(self.kafka_topic, item['data'])
Service    |   File "/usr/local/lib/python2.7/site-packages/kafka/producer/kafka.py", line 543, in send
Service    |     self._wait_on_metadata(topic, self.config['max_block_ms'] / 1000.0)
Service    |   File "/usr/local/lib/python2.7/site-packages/kafka/producer/kafka.py", line 664, in _wait_on_metadata
Service    |     "Failed to update metadata after %.1f secs." % max_wait)
Service    | KafkaTimeoutError: KafkaTimeoutError: Failed to update metadata after 60.0 secs.
```
Versions: **"Python" 2.7** | **"kafka-python" 1.4.3** | and  **"spotify/kafka" Docker Image.**
I appreciate you help.

**Comment by kerol** [comment] 2019-03-13 09:08
I solved this problem after starting zookeeper on my macOS,
`brew services start kafka`
`brew services start zookeepr`
Btw, you can enable logging debug for more information:
```
import logging
logging.basicConfig(level=logging.DEBUG)
```
Because producer complained like this:
`DEBUG:kafka.client:Give up sending metadata request since no node is available`

**Comment by jeffwidman** [comment] 2019-03-15 07:06
The `1.4.5` release includes some commits that may fix some unconfirmed edge cases related to this. So if you're following this ticket, please retry with the latest release and let us know if you're still seeing this.

**Comment by parasjain** [comment] 2019-04-08 05:45
Has anyone found the concrete fix for this issue.
I am using the latest version` 1.4.5 `. 
The issue is while I am trying to send a json message within a **Django** based web application via producer, I am getting an error stating `KafkaTimeoutError: Failed to update metadata after 60.0 secs. `
However, if I run the same cod

[kafka-error.zip](https://github.com/dpkp/kafka-python/files/3052769/kafka-error.zip)

e as a standalone python script it runs fine.
The **Kafka Broker** and **Django Server** is running on the same local machine without any docker.

**Comment by jeffwidman** [comment] 2019-04-08 16:33
`1.4.6` was released earlier this week--there is a chance the fix for #1760 may also help with this, but not sure.

@parasjain can you try that and see if it helps?

**Comment by GeorgeXiaojie** [comment] 2019-04-18 08:35
Also encountered this problem in version 1.4.5, because my topic contains a comma (,)

**Comment by stevanmilic** [comment] 2019-05-16 13:07
I solved the problem by setting `KAFKA_ADVERTISED_HOST_NAME: 127.0.0.1` in `docker-compose.yml` for `wurstmeister/kafka` image.

**Comment by 0mars** [comment] 2019-06-19 15:24
any versions that actually works, can you share the docker-compose.yml if so, this issue is blocking me, I don't care which version to use

**Comment by jdolitsky** [comment] 2019-07-30 21:10
Ran into this issue in a Kubernetes environment (incubator/kafka Helm chart). The issue was that the number of replicas was less than the value for "default.replication.factor"

**Comment by apigban** [comment] 2019-08-20 12:06
> I got this message when trying to publish to a topic that doesn't exist.

THANK YOU!

**Comment by mrzhangboss** [comment] 2019-09-04 02:50
I meet this problem.My env is
`docker kafka image: wurstmeister/kafka:2.12-2.2.1`
and I fix it by
change image version to `wurstmeister/kafka:2.12-2.1.1` and add environment
`KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka1:9092`(change `kafka1` to your hostname)

**Comment by mujina93** [comment] 2019-11-13 13:04
I had this issue when porting the code from python 2 to 3.

Solved by changing
```python
kafkaValue = json.dumps(someDict, separators=(',', ':'))
producer.send(topic=bytes(topicNameAsString), key=bytes(someString), value=kafkaValue)
```

to
```python
kafkaValue = json.dumps(someDict, separators=(',', ':'))
producer.send(topic=topicNameAsString, key=bytes(someString, encoding='utf8'), value=bytes(kafkaValue, encoding='utf8'))
```

**Comment by avloss** [comment] 2019-12-21 00:36
can't believe this is still open - either topic is automatically created in both cases or in neither. This is puzzling!

**Comment by dpkp** [comment] 2019-12-29 19:00
I don't think this issue is terribly useful to keep open. There can be several causes for a timeout when fetching metadata. It could be networking, topic creation problems, topic naming problems, etc -- note all of the different "me too" explanations so far. I'm going to close this because it does not appear to be a specific bug in kafka-python that could be fixed with a PR.

**Closed by dpkp** 2019-12-29 19:00 UTC
Labels: bug, critical/stability

**Comment by davidzhx** [comment] 2020-03-17 18:21
run into the same error message, but the root cause in my case was related to an outdated invalid intermediate root cert in the CA Bundle, fixed once updated the intermediate cert.

**Comment by okazelnik** [comment] 2020-04-23 08:11
I'm still facing the problem in Kuberentes with kafka-python 1.4.7.
Someone found a solution for it?

**Comment by etos** [comment] 2020-07-08 08:05
If useful for anyone, I started to see this error, and turns out it began when someone turned disabled `auto.create.topics.enable`..  creating the topic manually resolved the issue

**Comment by kennyhe** [comment] 2020-07-19 01:46
I used docker-compose, in which the Kafka advertised listeners are:
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://broker:29092,PLAINTEXT_HOST://localhost:9092

Then I changed the port in python code to 29029 and solved the problem.

**Comment by iamanvesh** [comment] 2020-09-27 21:28
I was publishing to `None` topic. Fixed after changing the topic's name.

**Comment by nagi49000** [comment] 2022-05-01 20:33
Very confusing how everyone has had this problem for years, and no fixes have been put in

**Comment by wizeankitbhardwaj** [comment] 2022-06-26 05:02
> I've also noticed that using kafka-python in the interpreter works just fine, with the exact same bootstrap_servers and everything else. The bug only surfaces when executed as part of a Python program.

not for me. Its same in cmd also.

**Comment by joaoFTH7** [comment] 2022-08-17 03:19
I use docker in VM Ubuntu 20.04 LTS with Bridge network interface and my host is a Windows 10, when i try to consume or produce topics from Windows always receive timeout errors, to resolve this error **kafka.common.KafkaTimeoutError: ('Failed to update metadata after %s secs.', 60.0)**, in docker-compose i set `KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://192.168.3.7:9092,PLAINTEXT_INTERNAL://broker:29092`, in your case just change 192.168.3.7 for your VM IP addres, broker is the container name and is just used to communicate with others containers

**Comment by siavashoh** [comment] 2023-02-17 16:45
I was facing the same issue. I was using docker-compose.  I realized the problem was from the Kafka listeners. So I update  Kafka environments to this: (I'm not sure which line fixed it's but it working now)

- KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
- KAFKA_CFG_LISTENERS=INTERNAL://:9093,OUTSIDE://:9092
- KAFKA_CFG_ADVERTISED_LISTENERS=INTERNAL://kafka:9093,OUTSIDE://kafka:9092
- KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=INTERNAL:PLAINTEXT,OUTSIDE:PLAINTEXT
- KAFKA_CFG_INTER_BROKER_LISTENER_NAME=INTERNAL
- ALLOW_PLAINTEXT_LISTENER=yes

**Comment by Anku1024** [comment] 2024-04-01 22:14
producer = KafkaProducer(**producer_config)
        
            # Produce a message
            future = producer.send(topic_name,  key=b'ping', value=b'1234')# this line could resolve issue
                    
            # Block for 'synchronous' sends
            record_metadata = future.get(timeout=10)
        
            # Print metadata
            print(record_metadata.topic)
            print(record_metadata.partition)
            print(record_metadata.offset)
        
            # Produce keyed messages to enable hashed partitioning
            producer.send(topic_name, key=b'foo', value=b'bar')
        
            # Define success and error callbacks
            def on_send_success(record_metadata):
                print(record_metadata.topic)
                print(record_metadata.partition)
                print(record_metadata.offset)
        
            def on_send_error(excp):
                log.error('I am an errback', exc_info=excp)
        
            # Produce asynchronously with callbacks
            producer.send(topic_name, b'raw_bytes').add_callback(on_send_success).add_errback(on_send_error)
        
            # Block until all async messages are sent
            producer.flush()

**Comment by XuSShuai** [comment] 2024-06-20 09:26
remove `security_protocol="SSL"` can work for me.
