### ISSUE TITLE
Consumer overruns its session timeout, drops out of the group and never rejoins--stuck in zombie state.

### ISSUE THREAD

**Issue by infecto** [dpkp/kafka-python#1435] opened 2018-03-10 00:22 UTC
We just upgraded to 1.4.1 and I am noticing new behavior. It looks like a consumer is dropping out of the group and not automatically rejoining. 

In our logs the only similarity I have noticed is the following logs. Could be unrelated.

```
INFO:kafka.coordinator:Leaving consumer group
```
After that message the only other logs I see are idle connections getting closed.
```
INFO:kafka.client:Closing idle connection 14, last active 540000 ms ago
```

The service we run via supervisor just sits there and the consumers are no longer part of the group.

I am still digging through the behavior of kafka-python to understand why we are dropping out of the consumer group. I am going to poke around on the assumption that the worker is leaving the group and not rejoining. Will update when I see something.

This may be related to https://github.com/dpkp/kafka-python/issues/1418 but not sure based on the users input.

**Comment by dpkp** [comment] 2018-03-10 01:26
Can you enable debug logs and see if anything sticks out ?

**Comment by infecto** [comment] 2018-03-10 17:58
Working on getting that turned on fully now. At the same time trying to replicate in a development environment.

**Comment by infecto** [comment] 2018-03-13 21:32
@dpkp Looking into if I have something misconfigured or not here. Look at kafka-python source now but appears that I am reaching `self.coordinator.heartbeat.poll_timeout_expired` and never rejoining. I don't quite know how to make of this behavior. I feel that perhaps an exception should be raised here or there should be some attempt to automatically rejoin the group. 

I don't have full depth on this check yet though so I am just speculating.

```
DEBUG:kafka.coordinator:Heartbeat: worker.w.temp_actions_test_worker[7] kafka-python-1.4.1-eb9309fd-53d3-4f50-9f2b-5490e6e039d8
DEBUG:kafka.protocol.parser:Sending request HeartbeatRequest_v0(group='worker.w.temp_actions_test_worker', generation_id=7, member_id=u'kafka-python-1.4.1-eb9309fd-53d3-4f50-9f2b-5490e6e039d8')
DEBUG:kafka.conn:<BrokerConnection node_id=7 host=<host>> Request 1369: HeartbeatRequest_v0(group='worker.w.temp_actions_test_worker', generation_id=7, member_id=u'kafka-python-1.4.1-eb9309fd-53d3-4f50-9f2b-5490e6e039d8')
DEBUG:kafka.protocol.parser:Received correlation id: 1369
DEBUG:kafka.protocol.parser:Processing response HeartbeatResponse_v0
DEBUG:kafka.conn:<BrokerConnection node_id=7 host=<host>> Response 1369 (25.6671905518 ms): HeartbeatResponse_v0(error_code=0)
DEBUG:kafka.coordinator:Received successful heartbeat response for group worker.w.temp_actions_test_worker
DEBUG:kafka.coordinator:Not ready to heartbeat, waiting
DEBUG:kafka.coordinator:Not ready to heartbeat, waiting
DEBUG:kafka.coordinator:Not ready to heartbeat, waiting
DEBUG:kafka.coordinator:Not ready to heartbeat, waiting
DEBUG:kafka.coordinator:Not ready to heartbeat, waiting
DEBUG:kafka.coordinator:Not ready to heartbeat, waiting
DEBUG:kafka.coordinator:Not ready to heartbeat, waiting
DEBUG:kafka.coordinator:Not ready to heartbeat, waiting
DEBUG:kafka.coordinator:Not ready to heartbeat, waiting
DEBUG:kafka.coordinator:Not ready to heartbeat, waiting
DEBUG:kafka.coordinator:Not ready to heartbeat, waiting
DEBUG:kafka.coordinator:Not ready to heartbeat, waiting
DEBUG:kafka.coordinator:Not ready to heartbeat, waiting
DEBUG:kafka.coordinator:Not ready to heartbeat, waiting
DEBUG:kafka.coordinator:Heartbeat: worker.w.temp_actions_test_worker[7] kafka-python-1.4.1-eb9309fd-53d3-4f50-9f2b-5490e6e039d8
DEBUG:kafka.protocol.parser:Sending request HeartbeatRequest_v0(group='worker.w.temp_actions_test_worker', generation_id=7, member_id=u'kafka-python-1.4.1-eb9309fd-53d3-4f50-9f2b-5490e6e039d8')
DEBUG:kafka.conn:<BrokerConnection node_id=7 host=<host> port=9092> Request 1370: HeartbeatRequest_v0(group='worker.w.temp_actions_test_worker', generation_id=7, member_id=u'kafka-python-1.4.1-eb9309fd-53d3-4f50-9f2b-5490e6e039d8')
DEBUG:kafka.coordinator:Not ready to heartbeat, waiting
DEBUG:kafka.protocol.parser:Received correlation id: 1370
DEBUG:kafka.protocol.parser:Processing response HeartbeatResponse_v0
DEBUG:kafka.conn:<BrokerConnection node_id=7 host=<host> port=9092> Response 1370 (1.5561580658 ms): HeartbeatResponse_v0(error_code=0)
DEBUG:kafka.coordinator:Received successful heartbeat response for group worker.w.temp_actions_test_worker
DEBUG:kafka.coordinator:Not ready to heartbeat, waiting
DEBUG:kafka.coordinator:Not ready to heartbeat, waiting
DEBUG:kafka.coordinator:Not ready to heartbeat, waiting
DEBUG:kafka.coordinator:Not ready to heartbeat, waiting
DEBUG:kafka.coordinator:Not ready to heartbeat, waiting
DEBUG:kafka.coordinator:Not ready to heartbeat, waiting
DEBUG:kafka.coordinator:Not ready to heartbeat, waiting
DEBUG:kafka.coordinator:Not ready to heartbeat, waiting
DEBUG:kafka.coordinator:Not ready to heartbeat, waiting
DEBUG:kafka.coordinator:Heartbeat poll expired, leaving group
INFO:kafka.coordinator:Leaving consumer group (worker.w.temp_actions_test_worker).
DEBUG:kafka.protocol.parser:Sending request LeaveGroupRequest_v0(group='worker.w.temp_actions_test_worker', member_id=u'kafka-python-1.4.1-eb9309fd-53d3-4f50-9f2b-5490e6e039d8')
DEBUG:kafka.conn:<BrokerConnection node_id=7 host=<host> port=9092> Request 1371: LeaveGroupRequest_v0(group='worker.w.temp_actions_test_worker', member_id=u'kafka-python-1.4.1-eb9309fd-53d3-4f50-9f2b-5490e6e039d8')
DEBUG:kafka.protocol.parser:Received correlation id: 1371
DEBUG:kafka.protocol.parser:Processing response LeaveGroupResponse_v0
DEBUG:kafka.conn:<BrokerConnection node_id=7 host=<host> port=9092> Response 1371 (2.7539730072 ms): LeaveGroupResponse_v0(error_code=0)
DEBUG:kafka.coordinator:LeaveGroup request for group worker.w.temp_actions_test_worker returned successfully
DEBUG:kafka.coordinator:Group state is not stable, disabling heartbeats
DEBUG:kafka.coordinator:Heartbeat disabled. Waiting
```

**Comment by infecto** [comment] 2018-03-13 21:33
^ Forgot to mention that the remaining logs are just some metadata requests and then idle connection cleanup.

**Comment by infecto** [comment] 2018-03-13 23:28
Trying to separate our own implementation details and kafka-python....

We built a wrapper our kafka-python to standardized how developers interact with the library. Historically we ran consumers by running `message = next(self._kafka_client)` inside of a while loop until a time or message size limit was hit. `_kafka_client` represents an instance of kafka-python's `KafkaConsumer`. We manually commit after processing of messages. We have been running like this for 1-2 years. 

I am going to try and sanitize the logs before the snippet I provided. So far I am seeing proper fetching and committing of offsets until the very end where I see no new work but I am not seeing a reason why yet.

**Comment by dpkp** [comment] 2018-03-22 19:42
This log `DEBUG:kafka.coordinator:Heartbeat poll expired, leaving group` means that you are not processing messages fast enough to keep up with your configured `max_poll_interval_ms` . What is that configured to and is it possible that your consumer application might not be able to keep up?

It is also possible that there is a bug in the kafka-python implementation that is triggering a heartbeat poll expiration too early. But I haven't noticed anything yet myself.

**Comment by infecto** [comment] 2018-03-26 18:07
I setup a test outside of our production use for the past week and was not able to replicate the problem. I am going to try and get proper logging running in our production environment and I might be able to at least narrow this down between a code issue between our wrapper or something happening in kafka-python.

@dpkp Even if we are not keeping up with `max_poll_interval_ms` should the consumer not try to restart itself?

**Comment by NoneGG** [comment] 2018-06-13 08:41
I have a similar problem with a consumer(`session_timeout` & `max_poll_interval` are set to default value) disable auto-commit (each msg is proceeded in about 3 ms)

This app depends on kafka-python v1.3.1 and is update to kafka-python v1.4.2 recently.
I doubt if it is caused by the backend heartbeat thread.

### log
```
 Marking the coordinator dead (node 1) for group bvc_disp_cache: Heartbeat session expired.
[I 180612 21:10:21 cluster         : 349] Group coordinator for bvc_disp_cache is BrokerMetadata(nodeId=1, host=host, port=port, rack=None)
[I 180612 21:10:21 base            : 676] Discovered coordinator 1 for group bvc_disp_cache
[W 180612 21:10:25 base            : 823] Heartbeat: local member_id was not recognized; this consumer needs to re-join

Then the log stock here, no more messages are proceeded and so i have to stop the process.
From 

[I 180613 07:36:40 prism_charger   :  93] Catch SIGNAL:15, resign heartbeat and release redis lock.
[I 180613 07:36:40 messages        :  83] Ready to exit
[I 180613 07:36:40 base            : 731] Stopping heartbeat thread
[I 180613 07:36:40 conn            : 710] <BrokerConnection node_id=1 host=host<connected> [IPv4 (host, port)]>: Closing connection. 

```

**Comment by jeffwidman** [comment] 2018-06-13 20:37
@NoneGG please move this to a separate ticket as the log output looks different, so probably a different issue... Also, what version of the broker are you talking to?

**Comment by NoneGG** [comment] 2018-06-14 03:09
@jeffwidman Kafka is of release 0.10.1, i am not sure if it is a different issue. I try to rollback kafka-python to v1.3.5 and chang the log level to DEBUG to log the problem detail. But the problem does not take place again today

**Comment by licy121** [comment] 2018-09-17 12:14
> @jeffwidman Kafka is of release 0.10.1, i am not sure if it is a different issue. I try to rollback kafka-python to v1.3.5 and chang the log level to DEBUG to log the problem detail. But the problem does not take place again today

Hi,I have a same problem with you
Have you got the root reason?

**Comment by jeffwidman** [comment] 2018-12-19 10:31
Hitting this myself. The logs make it clear this application didn't process its data fast enough, so when `max_poll_interval_ms` was hit, the heartbeat thread proactively left the group:

    2018-12-18 14:13:58,060 INFO            app_logging            do_info:24      26986   139930134464256 Message XXX successfully processed
    2018-12-18 14:13:58,089 INFO            app_logging            do_info:24      26986   139930134464256 Message XXX successfully processed
    2018-12-18 14:24:14,933 WARNING         base                    _run_once:971   26986   139929655580416 Heartbeat poll expired, leaving group
    2018-12-18 14:24:14,934 INFO            base                    maybe_leave_group:756   26986   139929655580416 Leaving consumer group (app_group).
    2018-12-18 14:28:57,898 INFO            client_async            _maybe_close_oldest_connection:897      26986   139930134464256 Closing idle connection 5, last active 900500 ms ago
    2018-12-18 14:28:57,898 INFO            conn                    close:710       26986   139930134464256 <BrokerConnection node_id=5 host=kafka05.net:9092 <connected> [IPv4 ('172.x.x.x', 9092)]>: Closing connection.

I realize the choice of what to do when the consumer times out is highly application-dependent. In this case, similar to @infecto above, I want the consumer to try to rejoin the group and continue. 

Before the addition of the background heartbeat thread, overrunning the session timeout would eventually throw a `CommitFailedError` which we would catch and then re-join the group.

However, now there's no exception raised, so I'm not seeing a clean way for the application to realize it's no longer part of the consumer group.

@dpkp  / @tvoinarovskyi any ideas?

**Comment by vkjv** [comment] 2019-02-16 08:28
I have a similar problem. My kafka consumer do not receive all the messages posted to kafka topic. If I look at the kafka logs of the topic, I see more messages than what was received by consumer. 
For some of the messages, the time taken for processing is going beyond request_timeout. And there were warnings in the logs saying, Hearbeat session expired, and
WARNING:kafka.coordinator.consumer:Auto offset commit failed for group <group_id>: CommitFailedError: Commit cannot be completed since the group has already
            rebalanced and assigned the partitions to another member.
            This means that the time between subsequent calls to poll()
            was longer than the configured max_poll_interval_ms, which
            typically implies that the poll loop is spending too much
            time message processing. You can address this either by
            increasing the rebalance timeout with max_poll_interval_ms,
            or by reducing the maximum size of batches returned in poll()
            with max_poll_records.
We are using iterator interface to retrieve messages. And kafka-python version is 1.4.4
Any help is much appreciated.

**Comment by jeffwidman** [comment] 2019-03-05 22:55
This ticket was getting difficult to follow with people adding comments about issues that were pretty clearly unrelated (and partially user errors), so I deleted some of those comments.

*Please file a new bug unless you are quite sure you are experiencing this particular bug.*

Other known sources of stuckness in `1.4.4`: #1691 and #1728.

As best I can tell, this particular bug is different than both of those.

**Comment by jeffwidman** [comment] 2019-03-14 21:39
@infecto I wonder if this is the same as #1728?

There a bunch of changes merged to `master` over the last week. Can you try and see if this is still an issue?

**Closed** 2019-04-03 18:26 UTC
Labels: help request

**Comment by meedeepak** [comment] 2020-08-13 12:05
Try setting `legacy_iterator=True` in `KafkaConsumer` or use `poll()` because somehow `next_v2` does't seems to work on of the class

**Comment by bkmead99** [comment] 2022-10-24 03:46
Bump. Still seeing this 'zombie state' occurring. Nothing logged in debug after it's encountered
![image](https://user-images.githubusercontent.com/63377230/197444741-d97ac3e1-a912-4578-bc05-ba42a4410c51.png)
