### ISSUE TITLE
Consumer blocks indefinitely in `poll` when assigned partitions and brokers are unavailable

### ISSUE THREAD

**Issue by nihb** [dpkp/kafka-python#1764] opened 2019-03-26 02:56 UTC
Firstly: thanks (!) for writing this library.
I'm not sure if this is user error, a bug or a feature, but the following blocks indefinitely on the poll() command (no broker needed) in python2 and python3 on 1.3.5, 1.4.3, 1.4.5 as well as on 1.4.6.dev:
```python
from kafka import KafkaConsumer, TopicPartition
# N.B. "yyy" does not resolve to any hostname on my network
consumer = KafkaConsumer(bootstrap_servers='yyy:9092', api_version='0.10.1')
consumer.assign([TopicPartition('zzz', 0)])
r_poll = consumer.poll(timeout_ms=1000)
```
I've also tested it by replacing "yyy" above with local hosts whose dns entries are defined but which have been turned off with the same results (blocks indefinitely). Adding `group_id` to KafkaConsumer also doesn't seem to help.

P.S. Removing the `api_version='0.10.1'` allows the KafkaConsumer() call to return immediately with no brokers available in 1.4.6.dev, blocks indefinitely on KafkaConsumer() in 1.4.5, returns immediately in 1.3.5.

**Comment by dpkp** [comment] 2019-03-26 04:28
This is the same issue as #1346 / KAFKA-6397

**Comment by nihb** [comment] 2019-03-26 04:51
Hi dpkp,
Thanks (!) for the quick response. So, if I understand correctly, it sounds like this is a fundamental issue with api_version=0.10.1.
I'll continue with my ugly workaround for the moment (using SIGALRM to break out of `poll()`, etc.), then try to get off this api altogether.
Cheers.

**Comment by dpkp** [comment] 2019-03-26 05:16
No, this is not specific to 0.10.1 or any particular API version. It is a
"bug" in the client code that does not pass the poll timeout into all
internal method calls. This has also been a bug in the Java client. If/when
it gets fixed, your consumer.poll call would return empty after the 1 sec
timeout you are passing.

**Comment by nihb** [comment] 2019-03-27 02:58
Hi dpkp,
Thanks (!) for the clarification. So in the example above, the use of api_version=0.10.1 seems to have poked this bug due to the call to KafkaConsumer() returning immediately followed by a call to poll() where things block, whereas when the api_version isn't forced to be 0.10.1 the KafkaConsumer() function raises an error before poll() gets called complaining that no brokers are available, the program exits and we don't get stuck with poll() blocking indefinitely.
Since I'd like to avoid poking this problem as much as possible, it sounds like KafkaConsumer() here might be my friend. So a quick question: if api_version=0.10.1 does the initial connection to the brokers occur in poll(), whereas in later APIs KafkaConsumer() already tries to start up some kind of dialogue (e.g. metadata) with them?

**Comment by dpkp** [comment] 2019-03-27 03:12
Without specifying an api_version we will do some initial magic "poking"
and try to guess the broker version. The error you are seeing is from this
version check, which is synchronous.

**Comment by jeffwidman** [comment] 2020-02-12 20:51
Closing as dupe of https://github.com/dpkp/kafka-python/issues/1346

**Closed by jeffwidman** 2020-02-12 20:51 UTC
