### ISSUE TITLE
Cluster communiction problems in 1.4.5 & 1.4.6

### ISSUE THREAD

**Issue by ov7a** [dpkp/kafka-python#1856] opened 2019-07-01 09:54 UTC
Sample code:

```
from kafka import KafkaConsumer
kafka_client = KafkaConsumer(bootstrap_servers = "node1:9093")
topic = "some topic"
partitions = kafka_client.partitions_for_topic(topic)
print(partitions)
kafka_client.close()	
```
I get `{0, 1, 2, 3, 4, 5, 6, 7}` in 1.4.4 and earlier versions, and `None` in 1.4.5 and 1.4.6.

Kafka version: 2.2.0

**Comment by zulrang** [comment] 2019-07-01 18:47
Having a similar issue: 

```
from kafka import KafkaProducer

producer = KafkaProducer(bootstrap_servers='localhost:9092')
for x in range(100):
    producer.send('test', "Message {}".format(x).encode('utf-8'))
```

And running the following (either before or after running the above script) results in nothing happening:

```
bin/kafka-console-consumer.sh --bootstrap-server localhost:9092 --topic test --from-beginning
```

**Comment by zahidzaman** [comment] 2019-07-09 02:29
Had same issue but got resolved when called kafka_client.topics() before kafka_client.partitions_for_topic(topic). I think follwing is the reason for failure https://kafka-python.readthedocs.io/en/master/apidoc/KafkaConsumer.html 

`This method first checks the local metadata cache for information about the topic. If the topic is not found (either because the topic does not exist, the user is not authorized to view the topic, or the metadata cache is not populated), then it will issue a metadata update call to the cluster.`

**Comment by jeffwidman** [comment] 2019-07-11 19:04
Dupe of #1774. This has already been fixed on `master` in https://github.com/dpkp/kafka-python/pull/1781... essentially some changes in `1.4.5` meant that the call would return `None` if the metadata hadn't yet been force fetched through another method, so we changed it to issue a call...
Hopefully we can get a release out in the next few weeks with this.

**Closed by jeffwidman** 2019-07-11 19:04 UTC
