### ISSUE TITLE
Help: Using kafka-python on Windows 

### ISSUE THREAD

**Issue by KyleGobel** [dpkp/kafka-python#586] opened 2016-03-13 23:12 UTC
Does this work on windows?  I can't seem to get a connection, though other libraries (c# for example) work fine.

Here is the output on windows 10 Python 2.7

```
Attempting to bootstrap via node at <connectioninfo>
No connection nodes found.  Trying disconnected nodes.
No luck.  Trying all broker metadata
No nodes found in metadata -- retrying bootstrap
Sleeping 0.0990 before bootstrapping again
Attempting to bootstrap via node at <connectioninfo>
Unable to bootstrap from <connectioninfo>
Traceback (most recent call last):
  File "C:/Users/kgobe/PycharmProjects/KafkaTest/test.py", line 15, in <module>
    producer = KafkaProducer(bootstrap_servers='<connectioninfo>')
  File "C:\Users\kgobe\Testing\lib\site-packages\kafka\producer\kafka.py", line 248, in __init__
    self.config['api_version'] = client.check_version()
  File "C:\Users\kgobe\Testing\lib\site-packages\kafka\client_async.py", line 635, in check_version
    connect(node_id)
  File "C:\Users\kgobe\Testing\lib\site-packages\kafka\client_async.py", line 598, in connect
    raise Errors.NodeNotReadyError(node_id)
kafka.common.NodeNotReadyError: None
```

Whereas the output of the same code running ubuntu 14.04 server is this

```
Attempting to bootstrap via node at <connectioninfo>
No connected nodes found. Trying disconnected nodes.
No luck. Trying all broker metadata
Initiating connection at node 0 at <full host name>
Node 0 connection state is <connected>
Broker is not v0.9 -- it did not recognize ListGroupsRequest
Node 0 connection state is <connected>
Broker version identified as 0.8.2
```

Apparently my broker is 0.8.2, if I upgrade to 0.9 will it work on windows?

**Comment by dpkp** [comment] 2016-03-14 03:14
The errors you posted suggest that this is a simple networking problem - the windows client is unable to open a simple socket connection to any host:port in your `bootstrap_servers` list. You might check that your broker's `advertised.host.name` and `advertised.port` are correctly configured.

**Comment by KyleGobel** [comment] 2016-03-14 04:22
my ``advertised.host.name`` is set to the ec2 public dns name, and the ``advertised.port`` is set to 9092.

It is odd that even with the linux client it doesn't find any connected nodes, tries disconnected nodes, and then tries all broker metadata and finally gets a connection.

I don't know a lot about kafka, but do you have any other ideas of what I should try?  It's tough here because it works with every other client I try except for python on windows.

**Comment by dpkp** [comment] 2016-03-14 06:12
can you enable DEBUG logging and post a more detailed log output?

**Comment by KyleGobel** [comment] 2016-03-14 11:44
I'm not very experienced with python, but I thought that was debug logging.

Here is my full script

```
from kafka import KafkaProducer
import logging
import sys

log = logging.getLogger("kafka.client")


def setup_logging():
    log.setLevel(logging.DEBUG)
    log.addHandler(logging.StreamHandler(sys.stdout))

if __name__ == "__main__":
    setup_logging()
    producer = KafkaProducer(bootstrap_servers=settings.bootstrap_server)
```

**Comment by dpkp** [comment] 2016-03-14 16:43
you can do this to configure logging (instead of your `setup_logging`):
```
logging.basicConfig(level=logging.DEBUG)
```

**Comment by dpkp** [comment] 2016-03-14 19:27
you might also take a look at Issue #568

**Comment by KyleGobel** [comment] 2016-03-15 00:10
Thanks, my debug output is:

```
DEBUG:kafka.producer.kafka:Starting the Kafka producer
DEBUG:kafka.client:Attempting to bootstrap via node at ec2-52-90-212-86.compute-1.amazonaws.com:9092
ERROR:kafka.conn:Connect attempt to <BrokerConnection host=ec2-52-90-212-86.compute-1.amazonaws.com port=9092> returned error 10035. Disconnecting.
ERROR:kafka.client:Unable to bootstrap from [('ec2-52-90-212-86.compute-1.amazonaws.com', 9092)]
DEBUG:kafka.client:No connected nodes found. Trying disconnected nodes.
DEBUG:kafka.client:No luck. Trying all broker metadata
ERROR:kafka.client:No nodes found in metadata -- retrying bootstrap
DEBUG:kafka.client:Sleeping 0.0960 before bootstrapping again
DEBUG:kafka.client:Attempting to bootstrap via node at ec2-52-90-212-86.compute-1.amazonaws.com:9092
ERROR:kafka.conn:Connect attempt to <BrokerConnection host=ec2-52-90-212-86.compute-1.amazonaws.com port=9092> returned error 10035. Disconnecting.
ERROR:kafka.client:Unable to bootstrap from [('ec2-52-90-212-86.compute-1.amazonaws.com', 9092)]
Traceback (most recent call last):
  File "C:/Users/kgobe/PycharmProjects/KafkaTest/test.py", line 9, in <module>
    producer = KafkaProducer(bootstrap_servers="ec2-52-90-212-86.compute-1.amazonaws.com:9092")
  File "C:\Users\kgobe\Testing\lib\site-packages\kafka\producer\kafka.py", line 248, in __init__
    self.config['api_version'] = client.check_version()
  File "C:\Users\kgobe\Testing\lib\site-packages\kafka\client_async.py", line 635, in check_version
    connect(node_id)
  File "C:\Users\kgobe\Testing\lib\site-packages\kafka\client_async.py", line 598, in connect
    raise Errors.NodeNotReadyError(node_id)
kafka.common.NodeNotReadyError: None
INFO:kafka.producer.kafka:Kafka producer closed
```
Same output using the ip address instead of the dns name.

Non standard parts of my server config are as follows

```
advertised.host.name=ec2-52-90-212-86.compute-1.amazonaws.com
advertised.port=9092
# interal ip of zookeeper on different box
zookeeper.connect=10.0.0.126:2182
```

The server setup is relatively new, and was setup exactly following 
https://www.digitalocean.com/community/tutorials/how-to-install-apache-kafka-on-ubuntu-14-04

with the only changes the changes above to the server.config.

The only thing maybe non standard here is zookeeper is running on a different machine.  Would that matter?

I can try setting up a new server with kafka and ZK on same box if you think that might shed light on the problem.

**Comment by dpkp** [comment] 2016-03-15 00:56
Thanks -- the logs show an unrecognized socket errno (`returned error 10035`). Fixing this will require modifying the kafka/conn.py socket code and possibly also kafka/client_async.py select calls. Unfortunately I do not have a windows machine to test on, so I cannot help here. But PRs welcome!

**Comment by dpkp** [comment] 2016-03-15 00:56
also, some helpful links:
https://msdn.microsoft.com/en-us/library/windows/desktop/ms740668(v=vs.85).aspx
http://itamarst.org/writings/win32sockets.html

**Comment by dpkp** [comment] 2016-03-15 00:58
closing as duplicate of #520

**Closed by dpkp** 2016-03-15 00:58 UTC

**Comment by KyleGobel** [comment] 2016-03-15 05:04
Ahhh, yeah I see now looking at the code.

This doesn't look to be windows compatible at all, I feel like that should be mentioned somewhere.  Though I think the only real changes would be changing the ``select`` stuff to use threads instead (maybe only on windows).  And for some reason I can't get the socket to connect unless it's in blocking mode...will have to read up on that.

Thanks for your help.
