### ISSUE TITLE
How to push uniqe messages in different partitions of a topic

### ISSUE THREAD

**Issue by avinash-mishra** [dpkp/kafka-python#1142] opened 2017-07-12 09:19 UTC
I have created a topic in Kafka with partition count 3 now in all these three partitions I want to push unique messages. Is there any way to do it? I checked `producer.send` pushes duplicate messages on all partitions.

For testing I am using following code:

```
from kafka import KafkaProducer
from kafka.errors import KafkaError

producer = KafkaProducer(bootstrap_servers=['localhost:9092'])

# Asynchronous by default
future = producer.send('my-topic', b'raw_bytes')
```
But it is sending duplicate messages on partitions.

**Comment by infecto** [comment] 2017-07-12 17:03
@avinash-mishra Are you sure they are truly duplicate and you did not send the same message more than once? Keep in mind that unless you destroyed the topic, it will retain all messages within your retention period, 7 days by default. Is it possible you have run this code more than once? 

To answer the first question, yes its possible to do this, in fact it is default behavior. The default pattern for Kafka publishing does not duplicate messages. The default partition strategy is random so when you send a message it will get sent to a random partition. You should not have to do anything special to achieve your requirement.

I would recommend setting up a tighter test to narrow down where the issue is.

- For now create a new topic for each test. I assume you have topic auto creation on so this should not be a problem. 
- In your message include a timestamp or perhaps a uuid so you can 100% positive that the messages are really duplicated.
- In the test setup maybe send a defined number of messages greater than 1. Then on consumption count the number of messages that are returned.

Let me know if I can help describe anything better.

**Comment by jeffwidman** [comment] 2017-07-25 04:12
I'm going to close this as most likely user misunderstanding/error. Happy to re-open if you can provide code reproducing a problem with `kafka-python`.

Thanks @infecto for the great answer!

**Closed by jeffwidman** 2017-07-25 04:12 UTC
