### ISSUE TITLE
Bad file descriptor

### ISSUE THREAD

**Issue by gsvijayraajaa** [dpkp/kafka-python#1086] opened 2017-04-24 14:01 UTC
Hi,

Can someone throw light on the below error? It happens randomly when the producer is trying to push the data.

 ERROR - Uncaught error in kafka producer I/O thread
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/kafka/producer/sender.py", line 60, in run
    self.run_once()
  File "/usr/local/lib/python3.4/dist-packages/kafka/producer/sender.py", line 147, in run_once
    (self._client.send(node_id, request)
  File "/usr/local/lib/python3.4/dist-packages/kafka/client_async.py", line 467, in send
    return self._conns[node_id].send(request)
  File "/usr/local/lib/python3.4/dist-packages/kafka/conn.py", line 540, in send
    return self._send(request)
  File "/usr/local/lib/python3.4/dist-packages/kafka/conn.py", line 559, in _send
    sent_bytes = self._sock.send(data[total_sent:])
OSError: [Errno 9] Bad file descriptor

**Comment by dpkp** [comment] 2017-04-24 17:21
Can you provide more context or a code snippet to reproduce?

**Comment by ivanmilinkovic** [comment] 2017-07-13 09:13
Hi,
I'm getting a similar error when I try to close a producer. It happens very randomly, every day or two so it is hard to reproduce.

Here is a code:

def send_partition(
    partition, topic, bootstrap_servers=['127.0.0.1:9092'], config={}
):
    partition = list(partition)
    if partition:
        try:
            from kafka import KafkaProducer
            connection = KafkaProducer(bootstrap_servers=bootstrap_servers)
            for item in partition:
                connection.send(topic, json.dumps(item).encode("utf-8"))
            connection.close()
        except:
            logger.error(
                "Error while saving partition to kafka topic {topic} "
                "using bootstrap servers {servers}".format(
                    topic=topic,
                    servers=", ".join(bootstrap_servers)
                ),
                exc_info=True
            )
            for item in partition:
                logger.error(item, exc_info=False)

Ad here is an error:

Traceback (most recent call last):
  File "/home/user/virtualenvs/project/lib/python3.5/site-packages/spark_utils/kafka.py", line 17,
 in send_partition
    connection.close()
  File "/home/user/virtualenvs/project/lib/python3.5/site-packages/kafka/producer/kafka.py", line 
419, in close
    self._sender.initiate_close()
  File "/home/user/virtualenvs/project/lib/python3.5/site-packages/kafka/producer/sender.py", line
 165, in initiate_close
    self.wakeup()
  File "/home/user/virtualenvs/project/lib/python3.5/site-packages/kafka/producer/sender.py", line
 311, in wakeup
    self._client.wakeup()
  File "/home/user/virtualenvs/project/lib/python3.5/site-packages/kafka/client_async.py", line 81
9, in wakeup
    if self._wake_w.send(b'x') != 1:
OSError: [Errno 9] Bad file descriptor

**Comment by larry-svds** [comment] 2017-08-31 01:04
I am also getting this every couple days.  Same as above only python 2.7

Code is: 

    producer = KafkaProducer(bootstrap_servers=kafka_service)

    for record in iter:
        txt = extract_tweet_text(record)
        polarity = compute_sentiment(txt)
        payload = {'tweet': txt, 'sentiment': polarity}
        msg = json.dumps(payload)
        producer.send(sentiment_topic, msg)
    producer.close()

17/08/30 09:27:16 ERROR Executor: Exception in task 0.0 in stage 64701.0 (TID 64701)
org.apache.spark.api.python.PythonException: Traceback (most recent call last):
  File "/opt/spark/spark-2.0.0/python/lib/pyspark.zip/pyspark/worker.py", line 172, in main
    process()
  File "/opt/spark/spark-2.0.0/python/lib/pyspark.zip/pyspark/worker.py", line 167, in process
    serializer.dump_stream(func(split_index, iterator), outfile)
  File "/opt/spark/spark-2.0.0/python/lib/pyspark.zip/pyspark/rdd.py", line 2371, in pipeline_func
  File "/opt/spark/spark-2.0.0/python/lib/pyspark.zip/pyspark/rdd.py", line 2371, in pipeline_func
  File "/opt/spark/spark-2.0.0/python/lib/pyspark.zip/pyspark/rdd.py", line 2371, in pipeline_func
  File "/opt/spark/spark-2.0.0/python/lib/pyspark.zip/pyspark/rdd.py", line 317, in func
  File "/opt/spark/spark-2.0.0/python/lib/pyspark.zip/pyspark/rdd.py", line 762, in func
  File "/opt/svds/sentiment/sentiment_processor/sentiment_processor.py", line 124, in process_tweet_iteration
    producer.close()
  File "/opt/miniconda2/envs/sentproc/lib/python2.7/site-packages/kafka/producer/kafka.py", line 424, in close
    self._sender.initiate_close()
  File "/opt/miniconda2/envs/sentproc/lib/python2.7/site-packages/kafka/producer/sender.py", line 165, in initiate_close
    self.wakeup()
  File "/opt/miniconda2/envs/sentproc/lib/python2.7/site-packages/kafka/producer/sender.py", line 311, in wakeup
    self._client.wakeup()
  File "/opt/miniconda2/envs/sentproc/lib/python2.7/site-packages/kafka/client_async.py", line 832, in wakeup
    if self._wake_w.send(b'x') != 1:
error: [Errno 9] Bad file descriptor

**Comment by larry-svds** [comment] 2017-08-31 01:12
The above is in a spark streaming context.  Once this happpens, it does not recover and continues to have problems.    Other applications using the kafka cluster do not have trouble reaching it.

**Comment by gsvijayraajaa** [comment] 2017-10-03 14:46
Any word  on this issue?

**Comment by martonpe** [comment] 2017-11-15 09:45
So has anything ever surfaced on this? Also do any of you have some sort of a workaround?

**Comment by jeffwidman** [comment] 2017-11-15 22:43
For people reporting this issue, we need more info to reproduce/debug. 

File descriptors typically are related to the interaction with the underlying OS, so what OS and kernel version are you observing this on? 

You can often find this by typing `uname -a` in a shell.

**Comment by martonpe** [comment] 2017-11-16 16:28
Ok, so I'm running inside Docker on Ubuntu Precise 12.04 LTS (x64). 

But what's probably more important is that just like seemingly everybody else before me, I'm producing to Kafka from a Spark context. The files I'm reading from are stored in S3. 

Here is my code:
```
products = spark.read.parquet('s3a://path/to/files/')

... some transformations ...

def publish_partition(elements):
        producer = KafkaProducer(
            bootstrap_servers=args.broker_list,
            key_serializer=lambda v: bytes(v, 'utf-8'),
            value_serializer=lambda v: json.dumps(v).encode('utf-8')
        )

        for variant in elements:
            producer.send(args.topic, variant.asDict(), key=args.partner + variant.id)

        producer.close()

products.select(
        ... column names ...
    ).foreachPartition(publish_partition)
```

And here is the full stacktrace:
```
org.apache.spark.api.python.PythonException: Traceback (most recent call last):
File "/usr/local/spark/python/lib/pyspark.zip/pyspark/worker.py", line 174, in main
  process()
File "/usr/local/spark/python/lib/pyspark.zip/pyspark/worker.py", line 169, in process
  serializer.dump_stream(func(split_index, iterator), outfile)
File "/usr/local/spark/python/lib/pyspark.zip/pyspark/rdd.py", line 2407, in pipeline_func
File "/usr/local/spark/python/lib/pyspark.zip/pyspark/rdd.py", line 2407, in pipeline_func
File "/usr/local/spark/python/lib/pyspark.zip/pyspark/rdd.py", line 2407, in pipeline_func
File "/usr/local/spark/python/lib/pyspark.zip/pyspark/rdd.py", line 346, in func
File "/usr/local/spark/python/lib/pyspark.zip/pyspark/rdd.py", line 794, in func
File "/usr/local/airflow/publish/tasks/publish_products.py", line 69, in publish_partition
  producer.close()
File "/usr/local/lib/python3.4/site-packages/kafka/producer/kafka.py", line 413, in close
  self._sender.initiate_close()
File "/usr/local/lib/python3.4/site-packages/kafka/producer/sender.py", line 165, in initiate_close
  self.wakeup()
File "/usr/local/lib/python3.4/site-packages/kafka/producer/sender.py", line 311, in wakeup
  self._client.wakeup()
File "/usr/local/lib/python3.4/site-packages/kafka/client_async.py", line 815, in wakeup
  if self._wake_w.send(b'x') != 1:
OSError: [Errno 9] Bad file descriptor
```

Let me know if you need more info and how I can help tracking this down.

**Comment by martonpe** [comment] 2017-11-24 17:48
Ok, so some more info:
* This only seems to happen with Kafka 0.10.x, not with 0.9 or 0.11
* Not sure by what change exactly, but fixed between 1.3.3 and 1.3.4

So if you're seeing this, you should probably just bump kafka-python. And I think this issue can be closed.

**Comment by jeffwidman** [comment] 2017-11-27 20:48
I'm closing for now, but I'm not convinced the root cause is actually fixed... but simpler to close until someone else reports as an error and then we can dig into it more.

**Closed by jeffwidman** 2017-11-27 20:48 UTC

**Comment by pouu69** [comment] 2018-07-31 04:36
If i close consumer, 'Bad file descriptor' error occurs.
