### ISSUE TITLE
Consumer object allows messages to be read in duplication, and by default

### ISSUE THREAD

**Issue by pauelm** [dpkp/kafka-python#2166] opened 2020-11-13 06:30 UTC
In the spirit of the "exactly once" event transaction handling of Kafka, when consumer objects are created from the KafkaConsumer method, consumers should NOT be able to read messages that have already been read by another consumer, AT LEAST by default, (with exceptions, such as when "from beginning" is specified).

As it currently stands in Kafka-Python 2.0.2, if there are multiple consumers mapped to same topic, they will read messages in duplication, and they will do this regardless of any other parameters specified at the time the consumer object is created.

This is a major bug, which currently prevents multiple consumers from being leveraged on a specific topic, and defeats the purpose of Kafka itself.

NOTE:
I have also read documentation that states that the message reading duplication can be prevented by making a call to consumer.commit() method, but that does not work either.  (There is a separate issue written up about this problem as well.)

I don't care how this issue is resolved.  I simply have the need for topic events to be read ONCE, regardless if a topic has 1 consumer, or 10 consumers, and a proper method to achieve it.  This method should also be the DEFAULT behavior, but currently is not.

Kafka-Python:  2.0.2
Python:  3.9.0

**Comment by Ormod** [comment] 2020-11-13 09:36
You might want to share a code snippet where you see this happening because it is very likely not a problem with the library but with how you use. By default different consumers within a group do only read a subset of the data.

**Comment by pauelm** [comment] 2020-11-13 10:57
It seems that the issue described should speak for itself.  The moment an event is read from a topic, that exact same event transaction should not be read _again_ by any consumer, unless consumer object instance is explicitly configured otherwise (e.g. "from_beginning"). 

consumer = KafkaConsumer(topic.name, group_id=kafka_client.group_id, bootstrap_servers-kafka_client.bootstrap_servers, enable_auto_commit=True)

consumer.subscribe([topic.name])

for msg in consumer:
  print(msg.value)

You asked for a snippet, so I provided it.  At a minimum, it would be great if you could share a snippet of code that can demonstrate an approach on how multiple consumers can read new events from a topic successfully without duplication (which is exactly how Kafka was intended to function fundamentally).  Moreover, if you are certain about how the library is supposed to work, and that with multiple consumers running, only a subset of data can be read, then it seems that it would be faster and make more sense to simply provide a demonstration of it, especially since most of the documentation does not provide workable examples of consumers using kafka-python outside of a very basic scenario, which is not useful for scenarios with multiple consumers on the same topic.

A library with consumer functionality that works differently than that (at least by default), runs counter to one of the key characteristics of how Kafka is supposed to function.  Unless explicitly specified differently, only unread messages should be read, regardless if you have 1 consumer or 10 consumers, otherwise it defeats the whole purpose, especially when scaling out with multiple consumers.  In most cases, reading / receiving duplicates is what users are wanting to avoid, and is one of the reasons why they become interested in using Kafka.

I should also note that I have tried multiple scenarios with calls to consumer.commit() method, but no luck there as well.  I have read that if this method is called after retrieving the previously unread event, that supposedly it will ensure that subsequent calls from a consumer will only retrieve the next, unread event after a producer has submitted it.  Not sure if that is supposed to be true or not, but oddly, while there is documentation that describes this method, I have not seen any example usage of this method where it eliminated duplicates, or even where it would function at all for that matter.  I have also tried other, older methods that were documented, with auto commit enabled / disabled, but that also did not appear to make any difference, but not surprised, as I am running 2.0.2, and some of those references were for a previous version.

Additional references:
https://kafka-python.readthedocs.io/en/2.0.1/index.html
https://kafka-python.readthedocs.io/en/1.0.2/usage.html

**Comment by dpkp** [comment] 2020-11-13 16:28
> In the spirit of the "exactly once" event transaction handling of Kafka, when consumer objects are created from the KafkaConsumer method, consumers should NOT be able to read messages that have already been read by another consumer, AT LEAST by default, (with exceptions, such as when "from beginning" is specified).

This is an incorrect understanding of the kafka system design. Kafka consumers can and will process the same message if they belong to different consumer groups, or belong to no consumer group. Furthermore, most message processing systems should expect that even when in the same group it is possible that network partitions or other quorum disruptions may cause multiple consumers in the same group to briefly consume the same message (for example, if consumer A receives a batch of messages but is exposed to a network failure prior to message commit, consumer B may be reassigned the batch of messages by the broker).

> As it currently stands in Kafka-Python 2.0.2, if there are multiple consumers mapped to same topic, they will read messages in duplication, and they will do this regardless of any other parameters specified at the time the consumer object is created.
> This is a major bug, which currently prevents multiple consumers from being leveraged on a specific topic, and defeats the purpose of Kafka itself.

Well, yes, this would be a major bug! I haven't been able to duplicate it myself, however. Can you provide any more specifics to help others reproduce? Have you looked at test/test_consumer_group.py ? Are you sure that each of your consumers is joining the same consumer group? You can check the logs to verify that this is happening. If your consumers do not join the same consumer group then you'll definitely see duplicate message processing, per explanation above re: group partitioning.

> I have also read documentation that states that the message reading duplication can be prevented by making a call to consumer.commit() method, but that does not work either. (There is a separate issue written up about this problem as well.)

Are you sure that you are providing a `group_id` to your KafkaConsumer when creating it? Something like this:
```
consumer = KafkaConsumer('my_favorite_topic', bootstrap_servers='host:port', group_id='my_favorite_group')
```

> I don't care how this issue is resolved. I simply have the need for topic events to be read ONCE, regardless if a topic has 1 consumer, or 10 consumers, and a proper method to achieve it. This method should also be the DEFAULT behavior, but currently is not.

I'm sorry you're having trouble getting setup with kafka-python. Please keep in mind that this is an entirely volunteer community of people (humans!) who have problems at work etc, just like you. Resolution of issues is primarily driven by people like you who not only identify problems, but also identify solutions and propose them via PRs. Please try to keep your attitude positive and assume the best of intent of others!

**Comment by pauelm** [comment] 2020-11-13 20:21
I can appreciate everything you are saying.  Also, although exactly once processing can be a difficult problem to solve, it is one of the cornerstones of Kafka, at least according to the creators of Kafka (Confluent), as well as Apache, and it one of the main reasons IT shops are attracted to Kafka.  

https://www.confluent.io/blog/exactly-once-semantics-are-possible-heres-how-apache-kafka-does-it/
https://cwiki.apache.org/confluence/display/KAFKA/KIP-98+-+Exactly+Once+Delivery+and+Transactional+Messaging

Perhaps others see using Kafka differently, or it is not important to their specific needs, so I can appreciate that as well.  I am sure there could be hundreds of ways that I could implement producers or consumers poorly and achieve undesirable results, but in the spirit of being productive, my focus is on identifying and understanding just ONE approach using the kafka-python library for exactly once event processing.  Outside of this issue, my producers and consumers have been working great and are very performant thus far.

Does kafka-python support exactly once processing for consumers?  If so, can you provide a working example that I can use as a starting point?  If kafka-python does not directly support this, then is there a way within kafka-python in which a consumer object can be created that filters only on unread events, then after each event is read, it can mark that event as read?  If so, what does that implementation look like?

If kafka-python library does not support exactly once event processing, then I will look to implement logic (on both the producer and consumer side for more of a belt and suspenders approach) that will collect specific data points for each event that is processed (since in my case, I will always know the exact data model), then compare values for matches (read: "duplicates"), and only submit and / or read events that do not match the previous event that was already processed, if that makes sense.  If I end up going this route, it is possible that there could be some sort of performance penalty, but this would be well worth it instead of having nasty problems of duplicates to try do deal with after the fact.

**Comment by dpkp** [comment] 2020-11-15 17:49
> Also, although exactly once processing can be a difficult problem to solve, it is one of the cornerstones of Kafka, at least according to the creators of Kafka (Confluent), as well as Apache, and it one of the main reasons IT shops are attracted to Kafka.
> 
> https://www.confluent.io/blog/exactly-once-semantics-are-possible-heres-how-apache-kafka-does-it/
> https://cwiki.apache.org/confluence/display/KAFKA/KIP-98+-+Exactly+Once+Delivery+and+Transactional+Messaging

The features you are referencing here are primarily related to Producer semantics, and leveraging those to improve the Kafka Streams API. More specifically, the feature introduced by KIP-98 is the ability to produce messages to multiple topics atomically. This doesn't seem related to the issue you originally raised wrt consumer processing.

But to close the loop on this reference, kafka-python does not provide a KafkaStreams implementation (though I worked on some prototyping a few years back). Transactional Producer semantics are also not yet supported, but are tracked here: #1063 . But 

> Does kafka-python support exactly once processing for consumers?

Please see my prior explanation. All Kafka consumers, including kafka-python, provide a consumer-group abstraction. Consumers in the same group should expect to process messages roughly "exactly once", but subject to caveats: (1) consumers must take care to manage commits relative to their side-effects properly. If you commit offsets prior to generating side-effects, your side-effects may not be processed if your consumer dies after committing but prior to generating a side-effect. Alternatively, if you decide to commit offsets after generating side-effects, you may find that your side-effects are triggered multiple times if your consumer dies after the side-effect but prior to committing offsets. (2) Consumer groups can be rebalanced in the event of network partitions. It is possible that a consumer may lose network with brokers and have its partition(s) reassigned without its knowledge. In this case, the consumer may be unaware that it should stop processing its current batch because it has been reassigned to another consumer. There are certainly ways to manage this, but as you say: exactly once processing can be a difficult problem to solve.

> If so, can you provide a working example that I can use as a starting point?

Yes, this is covered in the usage documentation here: https://kafka-python.readthedocs.io/en/master/

```
>>> from kafka import KafkaConsumer
>>> consumer = KafkaConsumer('my_favorite_topic', group_id='my_favorite_group')
>>> for msg in consumer:
...     print (msg)
```

To take a breath here, you seem to be having some very basic setup problems that are causing you frustration. The code to use a kafka consumer is dead simple. If the above does not perform as you expect, I'd suggest enabling python logging and seeing if you are experiencing any network or other configuration errors:
```
import logging
logging.basicConfig(level=logging.INFO)
```

**Closed** 2020-11-15 17:55 UTC

**Comment by pauelm** [comment] 2020-11-16 00:27
I am familiar with that usage example, and used something similar to that when I first started on a Kafka project but quickly determined that it was not adequate enough for my needs.  As a result, documentation on basic consumer examples do provide the information I am looking for.   In my scenarios, specifying a group_id in a call to KafkaConsumer does not appear assist with exactly once behavior in any way, so perhaps it has something to do with how topics are configured, but not sure about that. 

Also, with most Kafka scenarios I have seen, event data is being processed in Kafka with very basic producers and consumers, then there is a lot of manual intervention for business users, such as gathering data via KSQL, doing data dumps, data conversions, etc.  My producers collect event data from the source, include additional data processing, then submit to Kafka.  When my consumers read the event, they convert it back to human-readable format, then immediately submit to MongoDB as part of a fully-automated ETL pipeline.  I have done extensive functional, endurance, and performance test cycles with this setup, and literally after over 50M event transactions, everything has been reliable and running very smooth, with exception of undesirable duplicates.  Right now, any duplications I experience are not as as result of generated side effects, but because of event messages in consumer groups are literally being read more than once (which then would trigger additional side effects, of course). 

Given the situation and limitations you described, and that it would still be possible for duplicates in situations when there is a need to avoid them, and now confirming there is no out of the box solution to this in the library to deal with this complexity, then it becomes essential that I need to integrate a more robust solution.  I have an idea that I will investigate starting with the producer, then the consumer, then weigh out pros and cons, any performance penalties, etc.  I suspect that even with any noticeable performance penalty, it will still be far more beneficial and performant than simply producing and consuming with impunity, then implementing services to resolve and scrub duplicates after the fact.   Once I have it implemented, I will do extensive testing on this to be sure.

Thanks for the additional info.
