### ISSUE TITLE
ImportError: cannot import name IncompatibleBrokerVersion from kafka.errors

### ISSUE THREAD

**Issue by yangchanglin324** [dpkp/kafka-python#2211] opened 2021-03-12 10:13 UTC
Error when I calling KafkaConsumer

version:  python 3.7.3
code:  from kafka import KafkaConsumer
ERROR:   ImportError: cannot import name IncompatibleBrokerVersion from kafka.errors

![image](https://user-images.githubusercontent.com/14288294/110925819-9bdc4280-835e-11eb-9553-c1a7f8ea0d51.png)

**Comment by zbeedatm** [comment] 2021-04-05 13:44
Having the same!

**Comment by Felix-python** [comment] 2021-04-25 02:39
How can we solve it？

**Comment by zbeedatm** [comment] 2021-04-26 11:47
> How can we solve it？

In my case I had a local python file called kafka.py, so the import was referring to it instead on the kafka package... if it's the same case for you just change the file name and it will be resolved.

**Comment by jeffwidman** [comment] 2021-04-28 10:17
@Felix-python does ☝️ solve your issue?

**Comment by Felix-python** [comment] 2021-04-28 10:23
> > How can we solve it？
> 
> In my case I had a local python file called kafka.py, so the import was referring to it instead on the kafka package... if it's the same case for you just change the file name and it will be resolved.

Thanks a lot for your suggestions. Actually maybe some unknown errors occured. I just reopened the script, and the problem is solved.

**Comment by Felix-python** [comment] 2021-04-28 10:24
> @Felix-python does ☝️ solve your issue?
I  did not have a local python file called kafka.py. Actually maybe some unknown errors occured. I just reopened the script, and the problem is solved.

**Comment by jeffwidman** [comment] 2021-04-28 17:52
Thanks, going to close this then.

**Closed by jeffwidman** 2021-04-28 17:52 UTC

**Comment by manojt2501** [comment] 2021-05-09 07:51
no it isn't working

**Comment by ykocaturk** [comment] 2022-02-19 19:44
Isn't it ridiculous to ask for a file named kafka.py?

**Comment by shal-kumari** [comment] 2022-04-25 08:16
Facing this exact issue. I don't have any file named kafka.py either.

**Comment by buaatian** [comment] 2022-06-09 09:21
> > > How can we solve it？
> > 
> > 
> > In my case I had a local python file called kafka.py, so the import was referring to it instead on the kafka package... if it's the same case for you just change the file name and it will be resolved.
> 
> Thanks a lot for your suggestions. Actually maybe some unknown errors occured. I just reopened the script, and the problem is solved.

Reopen script is useful！
