### ISSUE TITLE
kafka 1.3.5 vs kafka-python 2.0.1

### ISSUE THREAD

**Issue by fortesp** [dpkp/kafka-python#2022] opened 2020-03-17 16:32 UTC
Hello guys,
I am just a bit confused and i would like someone to help me understand why there are two packages registered in PyPi with different names. I first thought it was from different developers, but that is obviously not the case.. 
I believe the maintainable package is the kafka-python by looking into the release history.
Still i have to ask, whats the purpose of the other one? :)
Thanks!

**Comment by jeffwidman** [comment] 2020-03-19 05:14
Dupe of https://github.com/dpkp/kafka-python/issues/1253 and https://github.com/dpkp/kafka-python/issues/1726

**Closed by jeffwidman** 2020-03-19 05:14 UTC
