### ISSUE TITLE
Help: Looping on KafkaConsumer simply reprocesses the same message forever

### ISSUE THREAD

**Issue by rjurney** [dpkp/kafka-python#996] opened 2017-02-27 03:23 UTC
Code looks like this, and it just loops over the same message forever instead of waiting for another message, or whatever. Using Python 3, with a local install of Kafka and all default settings.

Am I supposed to commit a new offset every time I read a message? I don't understand what I'm doing wrong.

```
# Setup Kafka
from kafka import KafkaConsumer
kafka_consumer = KafkaConsumer(
  config.kafka_topic,
  bootstrap_servers=[
    config.kafka_server + ':' + config.kafka_port
  ],
  api_version=(0, 10),
  group_id=0
)

for message_object in kafka_consumer:
  print(message_object)
```

**Comment by dpkp** [comment] 2017-02-28 18:02
Have you checked the logs? Try dropping to DEBUG and see what is going on internally. I suspect you are getting forced to do group rebalance for some reason. That would cause a "reset" to last committed offset. And if you haven't committed recently then you would see repeated messages.

**Comment by dpkp** [comment] 2017-03-06 17:53
I can't reproduce this. Feel free to reopen w/ logs or steps to reliably reproduce.

**Closed by dpkp** 2017-03-06 17:53 UTC
