### ISSUE TITLE
Why are there no releases to this repo since Sep 30, 2020

### ISSUE THREAD

**Issue by fbanu95** [dpkp/kafka-python#2351] opened 2023-01-30 16:49 UTC
Just wondering if we i should drop using this package and use confluent-kafka instead which is actively being maintained and released.

Any reason for no releases in the recent times ? Will there be a drop in support for this package ?

**Comment by jeffwidman** [comment] 2023-01-30 21:07
Duplicate of https://github.com/dpkp/kafka-python/issues/2290

**Closed by jeffwidman** 2023-01-30 21:07 UTC
