### ISSUE TITLE
IllegalStateException: connectionId has unexpected format

### ISSUE THREAD

**Issue by jencodingatwork** [dpkp/kafka-python#1072] opened 2017-04-06 16:05 UTC
Hello,

I am trying to run the example code with a 0.9.0 Kafka Server locally on my windows machine. The code executes successfully and I see the expected results, but I'm getting an error in the server logs. Is there a fix for this? Or a workaround?

Here is the error:

```
[2017-04-06 09:48:26,677] INFO [GroupCoordinator 0]: Preparing to restabilize group my-group with old generation 0
(kafka.coordinator.GroupCoordinator)
[2017-04-06 09:48:26,684] INFO [GroupCoordinator 0]: Stabilized group my-group generation 1 (kafka.coordinator.Grou
pCoordinator)
[2017-04-06 09:48:26,695] INFO [GroupCoordinator 0]: Assignment received from leader for group my-group for generat
ion 1 (kafka.coordinator.GroupCoordinator)
[2017-04-06 09:48:36,659] ERROR Processor got uncaught exception. (kafka.network.Processor)
java.lang.IllegalStateException: connectionId has unexpected format: fe80:0:0:0:4c4:fb33:5a68:14f8%11:9092-fe80:0:0
:0:4c4:fb33:5a68:14f8%11:56760
        at kafka.network.Processor$$anonfun$run$13$$anonfun$7.apply(SocketServer.scala:447)
        at kafka.network.Processor$$anonfun$run$13$$anonfun$7.apply(SocketServer.scala:447)
        at scala.Option.getOrElse(Option.scala:120)
        at kafka.network.Processor$$anonfun$run$13.apply(SocketServer.scala:446)
        at kafka.network.Processor$$anonfun$run$13.apply(SocketServer.scala:445)
        at scala.collection.Iterator$class.foreach(Iterator.scala:727)
        at scala.collection.AbstractIterator.foreach(Iterator.scala:1157)
        at scala.collection.IterableLike$class.foreach(IterableLike.scala:72)
        at scala.collection.AbstractIterable.foreach(Iterable.scala:54)
        at kafka.network.Processor.run(SocketServer.scala:445)
        at java.lang.Thread.run(Thread.java:745)
[2017-04-06 09:48:36,678] ERROR Processor got uncaught exception. (kafka.network.Processor)
java.lang.IllegalStateException: connectionId has unexpected format: fe80:0:0:0:4c4:fb33:5a68:14f8%11:9092-fe80:0:0
:0:4c4:fb33:5a68:14f8%11:56764
        at kafka.network.Processor$$anonfun$run$13$$anonfun$7.apply(SocketServer.scala:447)
        at kafka.network.Processor$$anonfun$run$13$$anonfun$7.apply(SocketServer.scala:447)
        at scala.Option.getOrElse(Option.scala:120)
        at kafka.network.Processor$$anonfun$run$13.apply(SocketServer.scala:446)
        at kafka.network.Processor$$anonfun$run$13.apply(SocketServer.scala:445)
        at scala.collection.Iterator$class.foreach(Iterator.scala:727)
        at scala.collection.AbstractIterator.foreach(Iterator.scala:1157)
        at scala.collection.IterableLike$class.foreach(IterableLike.scala:72)
        at scala.collection.AbstractIterable.foreach(Iterable.scala:54)
        at kafka.network.Processor.run(SocketServer.scala:445)
        at java.lang.Thread.run(Thread.java:745)
[2017-04-06 09:48:56,715] INFO [GroupCoordinator 0]: Preparing to restabilize group my-group with old generation 1
(kafka.coordinator.GroupCoordinator)
[2017-04-06 09:48:56,722] INFO [GroupCoordinator 0]: Group my-group generation 1 is dead and removed (kafka.coordin
ator.GroupCoordinator)
[2017-04-06 09:50:26,261] INFO [GroupCoordinator 0]: Preparing to restabilize group my-group with old generation 0
(kafka.coordinator.GroupCoordinator)
```

Here is the code I am running:

```
import threading
import logging
import time

from kafka import KafkaConsumer, KafkaProducer


class Producer(threading.Thread):
    daemon = True

    def run(self):
        producer = KafkaProducer(bootstrap_servers='localhost:9092')

        while True:
            producer.send('my-topic', b"test")
            producer.send('my-topic', b"\xc2Hello, stranger!")
            time.sleep(1)


class Consumer(threading.Thread):
    daemon = True

    def run(self):
        # join a consumer group
        consumer = KafkaConsumer('my-topic',
                                 bootstrap_servers='localhost:9092',
                                 auto_offset_reset='earliest')
        consumer.subscribe(['my-topic'])

        # The consumer iterator returns ConsumerRecords, which are simple
        # namedtuples that expose basic message attributes: topic,
        # partition, offset, key, and value
        for message in consumer:
            print (message)


def main():
    threads = [
        Producer(),
        Consumer()
    ]

    for t in threads:
        t.start()

    time.sleep(10)

if __name__ == "__main__":
    logging.basicConfig(
        format='%(asctime)s.%(msecs)s:%(name)s:%(thread)d:' +
               '%(levelname)s:%(process)d:%(message)s',
        level=logging.INFO
    )
    main()

```

Here is the end of output from the example. I believe the error is being thrown after the consumer prints the data but before the producer closes.
```
ConsumerRecord(topic=u'my-topic', partition=0, offset=4963, timestamp=None, timestamp_type=None, key=None, value='\xc2Hello, stranger!', checksum=-1090450220, serialized_key_size=-1, serialized_value_size=17)
ConsumerRecord(topic=u'my-topic', partition=0, offset=4964, timestamp=None, timestamp_type=None, key=None, value='test', checksum=1495943047, serialized_key_size=-1, serialized_value_size=4)
ConsumerRecord(topic=u'my-topic', partition=0, offset=4965, timestamp=None, timestamp_type=None, key=None, value='\xc2Hello, stranger!', checksum=-1090450220, serialized_key_size=-1, serialized_value_size=17)
ConsumerRecord(topic=u'my-topic', partition=0, offset=4966, timestamp=None, timestamp_type=None, key=None, value='test', checksum=1495943047, serialized_key_size=-1, serialized_value_size=4)
ConsumerRecord(topic=u'my-topic', partition=0, offset=4967, timestamp=None, timestamp_type=None, key=None, value='\xc2Hello, stranger!', checksum=-1090450220, serialized_key_size=-1, serialized_value_size=17)
2017-04-06 11:49:35,408.408.999919891:kafka.producer.kafka:6208:INFO:8748:Closing the Kafka producer with 999999999 secs timeout.
2017-04-06 11:49:35,408.408.999919891:kafka.conn:7624:INFO:8748:<BrokerConnection node_id=0 host=DULL-AI356580.us.ray.com/fe80::4c4:fb33:5a68:14f8%11 port=9092>: Closing connection. 

```

**Comment by dpkp** [comment] 2017-04-06 16:12
This looks like an error from the broker logs. Have you checked with the
Kafka server project? The issue seems related to ipv6

On Apr 6, 2017 9:05 AM, "jencodingatwork" <notifications@github.com> wrote:

Hello,

I am trying to run the example code with a 0.9.0 Kafka Server locally on my
windows machine. The code executes successfully and I see the expected
results, but I'm getting an error in the server logs. Is there a fix for
this? Or a workaround?

Here is the error:

[2017-04-06 09:48:26,677] INFO [GroupCoordinator 0]: Preparing to
restabilize group my-group with old generation 0
(kafka.coordinator.GroupCoordinator)
[2017-04-06 09:48:26,684] INFO [GroupCoordinator 0]: Stabilized group
my-group generation 1 (kafka.coordinator.Grou
pCoordinator)
[2017-04-06 09:48:26,695] INFO [GroupCoordinator 0]: Assignment
received from leader for group my-group for generat
ion 1 (kafka.coordinator.GroupCoordinator)
[2017-04-06 09:48:36,659] ERROR Processor got uncaught exception.
(kafka.network.Processor)
java.lang.IllegalStateException: connectionId has unexpected format:
fe80:0:0:0:4c4:fb33:5a68:14f8%11:9092-fe80:0:0
:0:4c4:fb33:5a68:14f8%11:56760
        at kafka.network.Processor$$anonfun$run$13$$anonfun$7.apply(SocketServer.scala:447)
        at kafka.network.Processor$$anonfun$run$13$$anonfun$7.apply(SocketServer.scala:447)
        at scala.Option.getOrElse(Option.scala:120)
        at kafka.network.Processor$$anonfun$run$13.apply(SocketServer.scala:446)
        at kafka.network.Processor$$anonfun$run$13.apply(SocketServer.scala:445)
        at scala.collection.Iterator$class.foreach(Iterator.scala:727)
        at scala.collection.AbstractIterator.foreach(Iterator.scala:1157)
        at scala.collection.IterableLike$class.foreach(IterableLike.scala:72)
        at scala.collection.AbstractIterable.foreach(Iterable.scala:54)
        at kafka.network.Processor.run(SocketServer.scala:445)
        at java.lang.Thread.run(Thread.java:745)
[2017-04-06 09:48:36,678] ERROR Processor got uncaught exception.
(kafka.network.Processor)
java.lang.IllegalStateException: connectionId has unexpected format:
fe80:0:0:0:4c4:fb33:5a68:14f8%11:9092-fe80:0:0
:0:4c4:fb33:5a68:14f8%11:56764
        at kafka.network.Processor$$anonfun$run$13$$anonfun$7.apply(SocketServer.scala:447)
        at kafka.network.Processor$$anonfun$run$13$$anonfun$7.apply(SocketServer.scala:447)
        at scala.Option.getOrElse(Option.scala:120)
        at kafka.network.Processor$$anonfun$run$13.apply(SocketServer.scala:446)
        at kafka.network.Processor$$anonfun$run$13.apply(SocketServer.scala:445)
        at scala.collection.Iterator$class.foreach(Iterator.scala:727)
        at scala.collection.AbstractIterator.foreach(Iterator.scala:1157)
        at scala.collection.IterableLike$class.foreach(IterableLike.scala:72)
        at scala.collection.AbstractIterable.foreach(Iterable.scala:54)
        at kafka.network.Processor.run(SocketServer.scala:445)
        at java.lang.Thread.run(Thread.java:745)
[2017-04-06 09:48:56,715] INFO [GroupCoordinator 0]: Preparing to
restabilize group my-group with old generation 1
(kafka.coordinator.GroupCoordinator)
[2017-04-06 09:48:56,722] INFO [GroupCoordinator 0]: Group my-group
generation 1 is dead and removed (kafka.coordin
ator.GroupCoordinator)
[2017-04-06 09:50:26,261] INFO [GroupCoordinator 0]: Preparing to
restabilize group my-group with old generation 0
(kafka.coordinator.GroupCoordinator)

Here is the code I am running:

import threading
import logging
import time

from kafka import KafkaConsumer, KafkaProducer


class Producer(threading.Thread):
    daemon = True

    def run(self):
        producer = KafkaProducer(bootstrap_servers='localhost:9092')

        while True:
            producer.send('my-topic', b"test")
            producer.send('my-topic', b"\xc2Hello, stranger!")
            time.sleep(1)


class Consumer(threading.Thread):
    daemon = True

    def run(self):
        # join a consumer group
        consumer = KafkaConsumer('my-topic',
                                 bootstrap_servers='localhost:9092',
                                 auto_offset_reset='earliest')
        consumer.subscribe(['my-topic'])

        # The consumer iterator returns ConsumerRecords, which are simple
        # namedtuples that expose basic message attributes: topic,
        # partition, offset, key, and value
        for message in consumer:
            print (message)


def main():
    threads = [
        Producer(),
        Consumer()
    ]

    for t in threads:
        t.start()

    time.sleep(10)

if __name__ == "__main__":
    logging.basicConfig(
        format='%(asctime)s.%(msecs)s:%(name)s:%(thread)d:' +
               '%(levelname)s:%(process)d:%(message)s',
        level=logging.INFO
    )
    main()


Here is the end of output from the example. I believe the error is being
thrown after the consumer prints the data but before the producer closes.

ConsumerRecord(topic=u'my-topic', partition=0, offset=4963,
timestamp=None, timestamp_type=None, key=None, value='\xc2Hello,
stranger!', checksum=-1090450220, serialized_key_size=-1,
serialized_value_size=17)
ConsumerRecord(topic=u'my-topic', partition=0, offset=4964,
timestamp=None, timestamp_type=None, key=None, value='test',
checksum=1495943047, serialized_key_size=-1, serialized_value_size=4)
ConsumerRecord(topic=u'my-topic', partition=0, offset=4965,
timestamp=None, timestamp_type=None, key=None, value='\xc2Hello,
stranger!', checksum=-1090450220, serialized_key_size=-1,
serialized_value_size=17)
ConsumerRecord(topic=u'my-topic', partition=0, offset=4966,
timestamp=None, timestamp_type=None, key=None, value='test',
checksum=1495943047, serialized_key_size=-1, serialized_value_size=4)
ConsumerRecord(topic=u'my-topic', partition=0, offset=4967,
timestamp=None, timestamp_type=None, key=None, value='\xc2Hello,
stranger!', checksum=-1090450220, serialized_key_size=-1,
serialized_value_size=17)
2017-04-06 11:49:35,408.408.999919891:kafka.producer.kafka:6208:INFO:8748:Closing
the Kafka producer with 999999999 secs timeout.
2017-04-06 11:49:35,408.408.999919891:kafka.conn:7624:INFO:8748:<BrokerConnection
node_id=0 host=DULL-AI356580.us.ray.com/fe80::4c4:fb33:5a68:14f8%11
port=9092>: Closing connection.


—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/dpkp/kafka-python/issues/1072>, or mute the thread

**Comment by jencodingatwork** [comment] 2017-04-06 16:21
You're right it does look like an ipv6 issue. Do you know if this is going to prevent the producer and consumer from functioning? (I need to know if I need to try and get approval for an upgrade)

Thank you!

**Comment by dpkp** [comment] 2017-04-06 17:01
I assume so, but you should check with the broker project. This is not a bug related to consumer or producer code.

**Closed by dpkp** 2017-04-06 17:01 UTC
