### ISSUE TITLE
Is this library maintained?  Is there a fork that is more maintained?

### ISSUE THREAD

**Issue by jimcarreer** [dpkp/kafka-python#2349] opened 2023-01-20 11:33 UTC
There has not been an update besides documentation fixes in 3 years, nor a release in the same amount of time.  The officially supported version of python is only 3.8 (we are now at 3.11), and the officially supported version of Kafka is 2.9 (I believe 3.2 is the latest).  Additionally the owner no longer appears active on github.

**Comment by jeffwidman** [comment] 2023-01-20 22:14
I can only speak for myself:
While I still have a soft-spot in my heart for both Python and Kafka, I haven't worked with either one professionally since 2019. I also now have 5 kids, so my life is a lot more full then when I first started maintaining this library...

I'm happy to continue to do drive-by maintainer duties like reviewing quick PR's, but the reality is many of the PR's that arrive for this repo are complex and require throughly reading the KIPs... which I just don't have time to do right now.

This project is still useful to many folks, particularly for one-off scripts, so it's worth keeping around. But unless/until someone steps up and starts maintaining it, it'll basically be in maintenance/keep-the-lights-on-and-no-more mode.

**Comment by jeffwidman** [comment] 2023-01-20 22:16
Closing as a duplicate of:
* https://github.com/dpkp/kafka-python/issues/2290#issuecomment-1009133967

In particular, see https://github.com/dpkp/kafka-python/issues/2290#issuecomment-1009133967

**Closed by jeffwidman** 2023-01-20 22:16 UTC

**Comment by jimcarreer** [comment] 2023-01-21 05:48
Thanks @jeffwidman I appreciate the response here, I've seen others suggest using confluent-python if kafka and python are used in a professional / production setting, would you recommend that?

**Comment by jeffwidman** [comment] 2023-01-21 06:36
Yes, in general as it is more feature complete at this point and has paid folks working on it to provide support. For a production app that expects to leverage more advanced Kafka functionality then the confluent library is definitely a better choice at this point in time.

The one major downside is that it's not pure python which makes debugging harder and also certain deployment situations more difficult. 

And this library, while lacking the latest features, still provides the basic publishing and consumer groups functionality that most folks need.

The other thing is the AdminClient is very straightforward to hack on since it's all pure python and easy to add/tweak commands since it's layered on top of the stable KafkaClient class which makes it easy to control exactly what is sent to the brokers.

So I expect this library to continue to fit well when a pure python solution is preferred, either for deployment reasons or for speed of rapid iteration/hacking on such as in DevOps scripts.
