### ISSUE TITLE
Consumer yields duplicate messages

### ISSUE THREAD

**Issue by fillest** [dpkp/kafka-python#1078] opened 2017-04-14 10:35 UTC
After upgrading from 1.3.1 to 1.3.3 we often (not always but there seems to be some pattern) get duplicated set of messages from consumer, e.g. if messages were `1`, `2` and `3`, on the first fetch we get `1, 2, 3` and on consequent fetches (auto_offset_reset='earliest') we get exactly `1, 2, 3, 1, 2, 3`. After downgrading back to 1.3.1 it works as expected again (no duplicates).
The consumer is single. The code can be reduced to:
```python
SECOND = 1000
session_timeout_ms = SECOND * 60 * 20
consumer = kafka.KafkaConsumer(
    'topicname',
    bootstrap_servers = ['%s:9092' % ip for ip in ...3 brokers here...],
    client_id = 'kafka_cat',
    group_id = 'kafka_cat',
    value_deserializer = cPickle.loads,
    auto_offset_reset = 'earliest',
    enable_auto_commit = False,
    consumer_timeout_ms = 1000 * 1,
    api_version = (0, 10),
    session_timeout_ms = session_timeout_ms,
    request_timeout_ms = session_timeout_ms + SECOND * 10,
    heartbeat_interval_ms = SECOND,
)
with contextlib.closing(consumer):
    for record in consumer:
        print "%s  %s %s" % (record.timestamp, record.offset, record.value)
```

broker version is 2.11-0.10.1.0
producer is confluent-kafka==0.9.2

**Comment by fillest** [comment] 2017-04-14 10:47
There also seems to be a little pause before the second pack appears e.g. "1, 2, 3 (~400-500ms) 1, 2, 3"

**Comment by jeffwidman** [comment] 2017-04-18 21:01
Maybe I'm missing something, but you have `enable_auto_commit = False` and I don't see any explicit commit in your example code. So it'd make sense that using `auto_offset_reset = 'earliest'` would result in duplicate messages. 

What I don't understand is why it would sometimes have duplicate messages and sometimes not... I haven't looked at the code, but I'm guessing the consumer maintains an internal offset within the `KafkaConsumer` process even though it isn't ever committed to the broker. 

Perhaps something changed in the 1.3.1 to 1.3.3 code that causes the consumer to more frequently lose connection to the broker, and then when that connection comes back it re-initializes it's offsets from the broker instead of pulling from it's in-memory offset? IDK...

**Comment by jianbin-wei** [comment] 2017-04-21 17:20
@dpkp , any idea about this duplicated messages?

**Comment by Drizzt1991** [comment] 2017-04-24 09:06
Even on reconnects, it should have not lost the offset. It could be something to do with 'consumer_timeout' maybe? It's only 1 second, maybe there's actually an outer loop there, @fillest Like, it just restarts the consumer every second, without a commit point.

**Comment by fillest** [comment] 2017-04-24 09:18
@Drizzt1991 There is no outer loop in the actual code.
In the actual code there is also a commit after processing all the messages. The problem happens regardless of presence of the commit.

**Comment by dpkp** [comment] 2017-10-22 05:33
Is this still happening on master? If so, debug logs would be helpful. Generally speaking, consumers should expect the possibility of duplicate messages. But certainly if you start getting duplicates where previously you did not, that is something we should investigate.

**Comment by dpkp** [comment] 2018-03-08 18:04
If a rebalance is triggered (for whatever reason) you should expect to see duplicate messages starting from your last committed offset. To get to the root cause of the rebalance, you will need to enable logging. If this is still happening on a more recent kafka-python release, please feel free to reopen and post logs.

**Closed by dpkp** 2018-03-08 18:04 UTC
