### ISSUE TITLE
Cannot send message with kafka python producer

### ISSUE THREAD

**Issue by fufjvnvnf** [dpkp/kafka-python#1154] opened 2017-07-21 03:33 UTC
I'm using Kafka-python 1.3.3 and Kafka_2.12-0.10.2.1. Here is my server config:
```
{  
   "type":"kafka",
   "dataSchema":{  
      "dataSource":"test",
      "parser":{  
         "type":"string",
         "parseSpec":{  
            "format":"csv",
            "columns":[  
               "a",
               "b",
               "timestamp"
            ],
            "timestampSpec":{  
               "column":"timestamp",
               "format":"auto"
            },
            "dimensionsSpec":{  
               "dimensions":[  
                  "a"
               ]
            }
         }
      },
      "metricsSpec":[  
         {  
            "type":"count",
            "name":"count"
         },
         {  
            "type":"doubleSum",
            "name":"b",
            "fieldName":"b",
            "expression":null
         }
      ],
      "granularitySpec":{  
         "type":"uniform",
         "segmentGranularity":"MINUTE",
         "queryGranularity":{  
            "type":"none"
         },
         "rollup":false,
         "intervals":null
      }
   },
   "tuningConfig":{  
      "type":"kafka",
      "maxRowsInMemory":75000,
      "maxRowsPerSegment":5000000,
      "intermediatePersistPeriod":"PT10M",
      "basePersistDirectory":"/data/soft-tools/imply-2.2.3/var/tmp/1500546736489-0",
      "maxPendingPersists":0,
      "indexSpec":{  
         "bitmap":{  
            "type":"concise"
         },
         "dimensionCompression":"lz4",
         "metricCompression":"lz4",
         "longEncoding":"longs"
      },
      "buildV9Directly":true,
      "reportParseExceptions":false,
      "handoffConditionTimeout":0,
      "resetOffsetAutomatically":false,
      "workerThreads":null,
      "chatThreads":null,
      "chatRetries":8,
      "httpTimeout":"PT10S",
      "shutdownTimeout":"PT80S"
   },
   "ioConfig":{  
      "topic":"test",
      "replicas":1,
      "taskCount":1,
      "taskDuration":"PT3600S",
      "consumerProperties":{  
         "bootstrap.servers":"localhost:9092"
      },
      "startDelay":"PT5S",
      "period":"PT30S",
      "useEarliestOffset":false,
      "completionTimeout":"PT1800S",
      "lateMessageRejectionPeriod":null,
      "skipOffsetGaps":false
   },
   "context":null
}
```
Here are my python code for sending my message:
```
producer=KafkaProducer(bootstrap_servers='123.207.238.179:9092', api_version=(0,10,2))
future = producer.send('test',b"'123',1,2013-08-31T01:02:33.000Z")
result = future.get(timeout=60)
```
And I got a timeout error for the last line. Is it a connection problem or is there something wrong with my message? Or should I not use Kafka 0.10.2.1?

**Comment by jeffwidman** [comment] 2017-07-25 04:02
This looks like a broker side issue, can you try producing to that kafka broker using the console producer shipped with kafka and verify that you can successfully produce? If not, you know the problem is with the broker. Kafka 0.10.2.1 should be fine.

I'm going to close this for now as reasonably confident it's a broker-side issue, happy to re-open if it's clear the issue is client-side.

**Comment by fufjvnvnf** [comment] 2017-07-25 04:04
I tried producing with the console producer and it works completely fine.

**Comment by jeffwidman** [comment] 2017-07-25 04:20
What was the exact command you executed for the console producer?

**Comment by dpkp** [comment] 2017-10-04 13:19
There isn't enough information here to reproduce, so I'm closing. Please feel free to reopen if this issue persists.

**Closed by dpkp** 2017-10-04 13:19 UTC
