### ISSUE TITLE
Socket disconnected

### ISSUE THREAD

**Issue by akheron** [dpkp/kafka-python#849] opened 2016-10-14 11:52 UTC
After upgrade to kafka-python 1.3.1, I get these errors 2-5 times an hour:

```
<BrokerConnection host=HOST_NAME/1.2.3.4 port=9092>: socket disconnected
```

Based on just the error message, I'm not sure why this happens or does the producer lose messages or not.

**Comment by kashifusmani** [comment] 2016-10-17 21:44
Any update on the reason of this issue? Does this error means that we need to worry about out messages?

**Comment by dpkp** [comment] 2016-10-17 21:52
kafka-python should be resilient to network failures, so I dont think the error message suggests message loss.

You might consider enabling a more verbose logging level to get deeper insight into the conditions causing the error.

**Comment by fillest** [comment] 2016-11-17 12:35
It is probably because of this: https://issues.apache.org/jira/browse/KAFKA-1282 I failed to find out if this nonsense could be completely disabled but looks like it can be increased via `connections.max.idle.ms` on the broker.

**Comment by jeffwidman** [comment] 2016-11-18 00:40
We are using kafka-python 0.9.5 against Kafka 0.8.2.1 cluster. We upgraded one broker in a underutilized cluster to Kafka 0.10.0.1 and saw an immediate spike in these errors. 

After debugging, it's because the new Kafka 10 broker is reaping idle connections, as alluded to above. 

The new Java consumers/producers/brokers all have a `connections.max.idle.ms` param, which defaults to slightly shorter on the clients than on the broker. It would be good to add this to `kafka-python` as well. Or at least the client should catch/retry the first time this happens, rather than bubbling it back up to the user.

**Comment by akheron** [comment] 2016-11-18 06:38
@jeffwidman Does this cause message loss for you or not?

**Comment by geoffreybauduin** [comment] 2017-02-13 08:51
@dpkp @akheron I can confirm that I lose the message. I am never able to read it from my consumers. The only error log I get (with future error callback) is also `ConnectionError('socket disconnected',)`, I get one of those every minutes on different instances running my producers.

**Comment by geoffreybauduin** [comment] 2017-02-14 09:43
After some digging, and from my understanding of the library, here are the conclusions I came up with.

- My production environment is an environment where TCP connections are regularly cut.
- My Kafka `connections.max.idle.ms` is the default value (10 minutes).

I often see future errors (all the time, "socket disconnected"). This kind of error is thrown from the `_recv` method of `kafka.conn.BrokerConnection`.
When such error happens (the socket did not return any data), then the connection is closed, failing all the in flight requests.

Can we have a proper workaround, or any fix inside the library to handle this case? This is a bit blocking, and I don't really like the idea of having a thread running every 5 minutes to recreate a producer to avoid any issues with socket connections.

**Comment by geoffreybauduin** [comment] 2017-02-26 10:44
@dpkp upping this topic, this is quite blocking on our side, and the only way to fix it is to instantiate a new producer before our socket closes, but it's a bit hacky, would like another way to solve this problem

**Comment by Xaelias** [comment] 2017-02-28 21:24
I think this issue is causing random failures on my end too. I end up with my consumer seemingly healthy but not consuming anything. It shows as "rebalancing" for the broker (which I think is bug with them, it's dead IMO). And it's a pain because I don't have a reliable way to detect it and at the very least spawn a new consumer...

**Comment by dpkp** [comment] 2017-03-09 19:53
At this point I am not sure what the goal of this issue is and I'm inclined to close it. We've added additional logging to the BrokerConnection class to help with socket debugging. If anyone has specific issues related to consumer or producer behavior recovering from server-side socket disconnects, please open separately.

**Closed by dpkp** 2017-03-09 19:53 UTC

**Comment by jeffwidman** [comment] 2017-03-09 20:36
@dpkp can you clarify the expected behavior here? 

`BrokerConnection` should auto-retry if the socket is disconnected, correct? Are messages that are queued but not sent before the socket was disconnected expected to be lost? 

Makes sense about folks opening more specific tickets with more detailed logging, it's just helpful to know what is actually considered an error vs expected behavior.

**Comment by dpkp** [comment] 2017-03-09 20:45
BrokerConnection does not auto-retry, no. Retry logic is upstream and depends on exception type and context.

KafkaProducer retries failed requests up to a certain number of times, configured by `retries`.

KafkaConsumer will generally refresh metadata and retry -- possibly to a new partition leader -- when a broker connection fails.
