### ISSUE TITLE
KafkaConsumer hang then infinite loop to re-enable Heartbeat

### ISSUE THREAD

**Issue by kenjones-cisco** [dpkp/kafka-python#1522] opened 2018-06-14 17:11 UTC
#### Summary
Using a similar pattern as shown in the [example](https://github.com/dpkp/kafka-python/blob/1.4.3/example.py) for the consumer implementation, I notice that after a period of time there are [intermittent hanging](#1520) of the process but then instead of recovery like the other scenario, an infinite loop starts trying to re-enable Heartbeat.

Snippet from logs
```
2018-06-14 16:57:35,373.373.4743595123291:kafka.cluster:140470597716712:DEBUG:14:Updated cluster metadata to ClusterMetadata(brokers: 5, topics: 1, groups: 0)
2018-06-14 16:59:33,757.757.3730945587158:kafka.coordinator.consumer:140470716779336:DEBUG:14:Sending offset-commit request with {TopicPartition(topic='mcmp.openstackrequest.dev', partition=0): OffsetAndMetadata(offset=1312, metadata='')} for group mcmp to 5
2018-06-14 16:59:33,757.757.6336860656738:kafka.protocol.parser:140470716779336:DEBUG:14:Sending request OffsetCommitRequest_v2(consumer_group='mcmp', consumer_group_generation_id=1047, consumer_id='ansible-driver-34-8nnkl-5de55184-5929-447d-b461-a64842865bb9', retention_time=-1, topics=[(topic='mcmp.openstackrequest.dev', partitions=[(partition=0, offset=1312, meta
data='')])])
2018-06-14 16:59:33,758.758.1315040588379:kafka.conn:140470716779336:DEBUG:14:<BrokerConnection node_id=5 host=msg-brk-dc3-005.cisco.com:9093 <connected> [IPv4 ('64.101.96.22', 9093)]> Request 5760: OffsetCommitRequest_v2(consumer_group='mcmp', consumer_group_generation_id=1047, consumer_id='ansible-driver-34-8nnkl-5de55184-5929-447d-b461-a64842865bb9', retention_ti
me=-1, topics=[(topic='mcmp.openstackrequest.dev', partitions=[(partition=0, offset=1312, metadata='')])])
2018-06-14 16:59:33,759.759.7224712371826:kafka.protocol.parser:140470716779336:DEBUG:14:Received correlation id: 5760
2018-06-14 16:59:33,759.759.8812580108643:kafka.protocol.parser:140470716779336:DEBUG:14:Processing response OffsetCommitResponse_v2
2018-06-14 16:59:33,760.760.089635848999:kafka.conn:140470716779336:DEBUG:14:<BrokerConnection node_id=5 host=msg-brk-dc3-005.cisco.com:9093 <connected> [IPv4 ('64.101.96.22', 9093)]> Response 5760 (2.0904541015625 ms): OffsetCommitResponse_v2(topics=[(topic='mcmp.openstackrequest.dev', partitions=[(partition=0, error_code=25)])])
2018-06-14 16:59:33,760.760.3387832641602:kafka.coordinator.consumer:140470716779336:DEBUG:14:OffsetCommit for group mcmp failed: [Error 25] UnknownMemberIdError: mcmp
2018-06-14 16:59:33,760.760.5140209197998:kafka.coordinator.consumer:140470716779336:WARNING:14:Auto offset commit failed for group mcmp: CommitFailedError: Commit cannot be completed since the group has already
            rebalanced and assigned the partitions to another member.
            This means that the time between subsequent calls to poll()
            was longer than the configured max_poll_interval_ms, which
            typically implies that the poll loop is spending too much
            time message processing. You can address this either by
            increasing the rebalance timeout with max_poll_interval_ms,
            or by reducing the maximum size of batches returned in poll()
            with max_poll_records.

2018-06-14 16:59:33,760.760.8494758605957:kafka.coordinator.consumer:140470716779336:ERROR:14:Offset commit failed: This is likely to cause duplicate message delivery
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/kafka/coordinator/consumer.py", line 515, in _maybe_auto_commit_offsets_sync
    self.commit_offsets_sync(self._subscription.all_consumed_offsets())
  File "/usr/local/lib/python3.6/site-packages/kafka/coordinator/consumer.py", line 508, in commit_offsets_sync
    raise future.exception # pylint: disable-msg=raising-bad-type
kafka.errors.CommitFailedError: CommitFailedError: Commit cannot be completed since the group has already
            rebalanced and assigned the partitions to another member.
            This means that the time between subsequent calls to poll()
            was longer than the configured max_poll_interval_ms, which
            typically implies that the poll loop is spending too much
            time message processing. You can address this either by
            increasing the rebalance timeout with max_poll_interval_ms,
            or by reducing the maximum size of batches returned in poll()
            with max_poll_records.

2018-06-14 16:59:33,761.761.1343860626221:kafka.coordinator.consumer:140470716779336:INFO:14:Revoking previously assigned partitions {TopicPartition(topic='mcmp.openstackrequest.dev', partition=0)} for group mcmp
2018-06-14 16:59:33,761.761.3024711608887:kafka.coordinator:140470716779336:INFO:14:(Re-)joining group mcmp
2018-06-14 16:59:33,761.761.5001201629639:kafka.coordinator:140470716779336:DEBUG:14:Sending JoinGroup (JoinGroupRequest_v2(group='mcmp', session_timeout=10000, rebalance_timeout=300000, member_id='', protocol_type='consumer', group_protocols=[(protocol_name='range', protocol_metadata=b'\x00\x00\x00\x00\x00\x01\x00\x19mcmp.openstackrequest.dev\x00\x00\x00\x00'), (pr
otocol_name='roundrobin', protocol_metadata=b'\x00\x00\x00\x00\x00\x01\x00\x19mcmp.openstackrequest.dev\x00\x00\x00\x00')])) to coordinator 5
2018-06-14 16:59:33,761.761.6772651672363:kafka.protocol.parser:140470716779336:DEBUG:14:Sending request JoinGroupRequest_v2(group='mcmp', session_timeout=10000, rebalance_timeout=300000, member_id='', protocol_type='consumer', group_protocols=[(protocol_name='range', protocol_metadata=b'\x00\x00\x00\x00\x00\x01\x00\x19mcmp.openstackrequest.dev\x00\x00\x00\x00'), (p
rotocol_name='roundrobin', protocol_metadata=b'\x00\x00\x00\x00\x00\x01\x00\x19mcmp.openstackrequest.dev\x00\x00\x00\x00')])
2018-06-14 16:59:33,763.763.603687286377:kafka.conn:140470716779336:DEBUG:14:<BrokerConnection node_id=5 host=msg-brk-dc3-005.cisco.com:9093 <connected> [IPv4 ('64.101.96.22', 9093)]> Request 5761: JoinGroupRequest_v2(group='mcmp', session_timeout=10000, rebalance_timeout=300000, member_id='', protocol_type='consumer', group_protocols=[(protocol_name='range', protoc
ol_metadata=b'\x00\x00\x00\x00\x00\x01\x00\x19mcmp.openstackrequest.dev\x00\x00\x00\x00'), (protocol_name='roundrobin', protocol_metadata=b'\x00\x00\x00\x00\x00\x01\x00\x19mcmp.openstackrequest.dev\x00\x00\x00\x00')])
2018-06-14 16:59:33,864.864.377498626709:kafka.coordinator:140470596655848:WARNING:14:Heartbeat session expired, marking coordinator dead
2018-06-14 16:59:33,864.864.5803928375244:kafka.coordinator:140470596655848:WARNING:14:Marking the coordinator dead (node 5) for group mcmp: Heartbeat session expired.
2018-06-14 16:59:34,902.902.9064178466797:kafka.protocol.parser:140470716779336:DEBUG:14:Received correlation id: 5761
2018-06-14 16:59:34,903.903.1319618225098:kafka.protocol.parser:140470716779336:DEBUG:14:Processing response JoinGroupResponse_v2
2018-06-14 16:59:34,903.903.3467769622803:kafka.conn:140470716779336:DEBUG:14:<BrokerConnection node_id=5 host=msg-brk-dc3-005.cisco.com:9093 <connected> [IPv4 ('64.101.96.22', 9093)]> Response 5761 (1139.8487091064453 ms): JoinGroupResponse_v2(throttle_time_ms=0, error_code=0, generation_id=1049, group_protocol='range', leader_id='logstash-0-a3492e83-4906-4075-92c8
-2c1803cbc845', member_id='ansible-driver-34-8nnkl-201be4fe-8ce3-4d8f-9b4c-d5c562a9f56d', members=[])
2018-06-14 16:59:34,903.903.583288192749:kafka.coordinator:140470716779336:DEBUG:14:Received successful JoinGroup response for group mcmp: JoinGroupResponse_v2(throttle_time_ms=0, error_code=0, generation_id=1049, group_protocol='range', leader_id='logstash-0-a3492e83-4906-4075-92c8-2c1803cbc845', member_id='ansible-driver-34-8nnkl-201be4fe-8ce3-4d8f-9b4c-d5c562a9f5
6d', members=[])
2018-06-14 16:59:34,903.903.7613868713379:kafka.coordinator:140470716779336:DEBUG:14:Sending follower SyncGroup for group mcmp to coordinator None: SyncGroupRequest_v1(group='mcmp', generation_id=1049, member_id='ansible-driver-34-8nnkl-201be4fe-8ce3-4d8f-9b4c-d5c562a9f56d', group_assignment=[])
2018-06-14 16:59:35,004.4.223346710205078:kafka.coordinator:140470596655848:DEBUG:14:Group state is not stable, disabling heartbeats
2018-06-14 16:59:35,004.4.490852355957031:kafka.coordinator:140470596655848:DEBUG:14:Heartbeat disabled. Waiting
2018-06-14 16:59:35,004.4.781484603881836:kafka.coordinator:140470596655848:DEBUG:14:Heartbeat re-enabled.
2018-06-14 16:59:35,004.4.961729049682617:kafka.coordinator:140470596655848:DEBUG:14:Heartbeat disabled. Waiting
```
More logs can be seen here: gist.github.com/kenjones-cisco/840335443287f13a88c6ae5a02d504f7

#### Version

	kafka-python       1.4.3

#### Configurations

	client_id == container `HOSTNAME`
	group_id set
	bootstrap_servers set
	auto_offset_reset = 'earliest'
	consumer_timeout_ms = 240000
	// all others are using the defaults

Looking to verify if this is a bug or possibly a configuration error.

**Comment by jeffwidman** [comment] 2020-02-12 21:20
There were some hanging issues in the early `1.4.x` series that have since been resolved.

Closing for now, but if you can still reproduce with the `2.0.0` release then post here and I'm happy to re-open.

**Closed by jeffwidman** 2020-02-12 21:20 UTC
