### ISSUE TITLE
KeyError: <kafka.producer.record_accumulator.RecordBatch object at 0x103a28150>

### ISSUE THREAD

**Issue by alirezastack** [dpkp/kafka-python#1226] opened 2017-09-21 13:20 UTC
When I try to send 50 messages/s a few messages are sent and then an error is raised as below giving keyError exception:

```
$ python producer_call.py
WARNING:kafka.producer.record_accumulator:Batch is already closed -- ignoring batch.done()
ERROR:kafka.future:Error processing errback
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/kafka/future.py", line 79, in _call_backs
    f(value)
  File "/Library/Python/2.7/site-packages/kafka/producer/sender.py", line 185, in _failed_produce
    self._complete_batch(batch, error, -1, None)
  File "/Library/Python/2.7/site-packages/kafka/producer/sender.py", line 243, in _complete_batch
    self._accumulator.deallocate(batch)
  File "/Library/Python/2.7/site-packages/kafka/producer/record_accumulator.py", line 507, in deallocate
    self._incomplete.remove(batch)
  File "/Library/Python/2.7/site-packages/kafka/producer/record_accumulator.py", line 587, in remove
    return self._incomplete.remove(batch)
KeyError: <kafka.producer.record_accumulator.RecordBatch object at 0x103a28150>
```

It is interesting that when I put `sleep(1)` it doesn't reach to error `_failed_produce` and thereby it does not raise `KeyError` exception.

My Producer is as below:
```

def __init__(self):
    self.producer = KafkaProducer(bootstrap_servers=bootstrap_servers, value_serializer=lambda m: 
    ujson.dumps(m).encode('ascii'), acks='all', linger_ms=1)

def cast(self, topic, payload):
    self.producer.send(topic=topic, value=payload)
```

When I remove `linger_ms` and do not tell Kafka to batch records that come in 1 millisecond delay. It does not raise any error, but on every execution it has different behavior. This is my sample producer:

```
for i in range(50):
    rpc.cast(topic='counter',
             payload={'count': i})
```

Sometimes it prints from 0 to 23 or sometime 40, the result is different. What is the issue and is this a misbehavior?

**Comment by dpkp** [comment] 2017-10-02 03:50
`self.producer.send(topic=topic, value=payload)` is an asynchronous call. There is no guarantee that your messages are actually sent, or, if so, how many. This is a bigger issue if you specify a linger_ms. That explains why you see different behavior each time. The error you see is likely caused by an implicit shutdown when your script ends before all data has been sent / while background threads are still processing batch sends. If you want to guarantee delivery (I assume you do if you set `acks='all'`), then you should call `.get(<timeout>)` on the result of each producer.send(). Alternately you can try `producer.flush()` though it does not guarantee acks.

**Comment by alirezastack** [comment] 2017-10-02 20:40
I actually want a guarantee for sent messages, but when I set `.get(<timeout>)` I should wait for the message. I want to send a message and do not want to wait for it. I have used `acks='all'` for that.

**Comment by dpkp** [comment] 2017-10-02 21:32
Ok. Well I think the tools are all here for you and so I'm going to close this as a non-bug / help request. I'd suggest trying 'producer.flush' or gathering futures in a list and calling .get() on each after processing a sufficient number for pipelining.

**Closed by dpkp** 2017-10-02 21:32 UTC
