### ISSUE TITLE
Auto-commit randomly stops working 

### ISSUE THREAD

**Issue by vartec** [dpkp/kafka-python#833] opened 2016-09-22 19:40 UTC
I'm seeing behavior when KafkaConsumer keeps consuming messages, but randomly stops committing offsets. After a restart works fine for a time after it gets stuck again.

See graph below, the values are as reported by the consumer. At two points `commit` value goes flat, and only picks up after the consumer is restarted. 

<img width="1362" alt="offsets graph" src="https://cloud.githubusercontent.com/assets/2284726/18762873/a7dfa078-80bf-11e6-8581-d6fba3db5626.png">

Setup details:
- Kafka-Python 1.3.1
- relevant KafkaConsumer settings
  - `api_version = (0,8,1)`  # to force committing to ZK
  - `enable_auto_commit = True`
  - `auto_commit_interval_ms = 2000`
- Kafka brokers 0.8.2.0 (cluster of 4)
  - `offset.storage=zookeeper`

**Comment by vartec** [comment] 2016-09-22 19:45
I am calling `.committed()`, `.position()` and `highwater()`, so possibly it's related to  https://github.com/dpkp/kafka-python/issues/722#issuecomment-226967114

**Comment by dpkp** [comment] 2016-09-24 20:35
Have you found anything in the logs?

**Comment by vartec** [comment] 2016-09-26 16:49
No, I haven't, but that might be due my log propagation settings. I'll update this as soon as I find out more.

**Comment by dpkp** [comment] 2016-11-19 20:04
I haven't been able to duplicate this directly, but one possible failure path for AutoCommit is this: we send a request to the broker. There is a network failure and the request fails. We do not get a socket event via selector (select / poll / epoll / kqueue / etc), and the request hangs indefinitely. No new autocommit request will be sent while an existing request is in-flight, so you might see exactly this behavior.

This failure scenario is addressed generally in #887 -- what do you think?

**Comment by vartec** [comment] 2016-11-20 18:33
There is a way that reliably triggers this: A rolling restart of a Kafka cluster. 

I don't know enough about AutoCommit internals, but IMO this would suggest that it's not only that timeouts, but also disconnects that are not checked. 

HTH

**Comment by dpkp** [comment] 2017-03-09 20:33
This may have been caused by #887 which was fixed in 1.3.2. Are you still seeing this issue with the latest kafka-python?

**Comment by vartec** [comment] 2017-03-09 21:53
@dpkp it's an intermittent and fairly random, so I have hard time reproducing it in dev environment, OTOH in production I've got a workaround (periodical manual commits), so it's hard to tell. 
Feel free to close this if you believe #887 fixes this issue.

**Comment by dpkp** [comment] 2018-03-23 01:25
I believe this was fixed in 1.3.2. Autocommits and heartbeats were also refactored substantially in 1.4 so I'm closing.

**Closed by dpkp** 2018-03-23 01:25 UTC
