### ISSUE TITLE
Consumer.partitions_for_topic requires metadata has already been fetched

### ISSUE THREAD

**Issue by ershashu** [dpkp/kafka-python#1774] opened 2019-04-01 18:02 UTC
Consumer 'partitions_for_topic' method is not returning the proper value. 

We have used the method : partitions_for_topic(topic) in our code, it was working fine with version 1.4.4 but getting an error in latest one (1.4.5)

**Comment by dpkp** [comment] 2019-04-02 02:49
`partitions_for_topic()` is currently non-blocking and will return empty if the client has not yet fetched metadata. It is likely that in the 1.4.4 you had already fetched metadata in the cache. I would suggest calling `consumer.topics()` to make a blocking metadata request prior to calling `partitions_for_topic()`

**Comment by Baisang** [comment] 2019-04-02 20:14
hey @dpkp, I recently ran into this issue as well in some scripts using version 1.4.2. The fix you described (fetching metadata with `consumer.topics()` works, but we never ran into the issue before (and it seems like the issue is more common now?). Not sure if something else changed (feels like it shouldn't have?) to explain this behavior.

**Comment by dpkp** [comment] 2019-04-03 04:31
I believe the java client has been updated to make a blocking request for metadata in `partitionsFor` -- we probably should do the same.

**Comment by jeffwidman** [comment] 2019-05-23 06:54
Fixed by #1781

**Closed by jeffwidman** 2019-05-23 06:54 UTC
