### ISSUE TITLE
Topic not available during auto-create initialization after topic deletion 

### ISSUE THREAD

**Issue by rolele** [dpkp/kafka-python#1088] opened 2017-04-26 10:17 UTC
I have a long running consumer process and I subscribe using pattern:
```
self.consumer = KafkaConsumer(bootstrap_servers="kafka:9092", group_id=self.group_id, auto_offset_reset='earliest', metadata_max_age_ms=3000)
self.consumer.subscribe(pattern='mytopic.*.test')
```

My process is running and I create a bunch of topics with pattern: mytopic.*.test 
and my consumer refresh and subcribe to those new topics periodicaly (3s)
 
It is working fine until I descide to clean a bunch of topic and I wait for a while (maybe while the topic is just marked for deletion it is still ok)
and then I get my logging that generate tons of logs very very fast: 
```
WARNING:kafka.cluster:Topic mytopic.11.test is not available during auto-create initialization
WARNING:kafka.cluster:Topic mytopic.12.test is not available during auto-create initialization
...
```
Those logging will not stop until the disk is full.

**Comment by jeffwidman** [comment] 2017-04-28 05:28
Are these logs happening on the broker or the consumer?

**Comment by rolele** [comment] 2017-04-28 07:45
Do you mean the broker as the kafka logs?
Those logs are generated by the python consumer. I think I have the line where this log is generqted is: https://github.com/dpkp/kafka-python/blob/82d50f443e04356b2f051f7476bb4b4f5bd700d2/kafka/cluster.py#L257

**Comment by Drizzt1991** [comment] 2017-04-29 00:41
Seems like a bug, but it is strange. The code above should have requested all topics metadata, but the behaviour suggests, that it actually requests a set of topics, that were created. Having debug logs to see what was queried would help )

**Comment by dpkp** [comment] 2019-12-29 20:09
This warning log happens when the broker returns LeaderNotAvailableError for a partition in the metadata response. When using patterns for subscription, kafka-python will always ask for all topics using either an empty topic list or no topic list, depending on the broker api version. So the behavior here is caused by the broker returning metadata for deleted topics, which is probably a broker bug. I assume it has been fixed in more recent broker versions.

Nonetheless, one thing we could do to improve this is to not log any metadata errors or warnings when we are doing a "full" topic metadata fetch. Most of these log messages are really only relevant when we are doing a specific topic request.

**Closed** 2019-12-30 00:07 UTC
