### ISSUE TITLE
Consumer poll skipping message without a timeout

### ISSUE THREAD

**Issue by bmoscon** [dpkp/kafka-python#1803] opened 2019-05-11 02:24 UTC
I'm writing roughly 60-80 messages a second to kafka. I'm attempting to poll with no arguments, and I'll typically get about 1/2 the expected messages the first time I poll, and then 0 messages on subsequent polls, even thought the offset continues to increase each time I poll (I'm checking with `end_offsets` and I see the offset increasing as expected). I've tried polling more frequently, less frequently, etc to no avail. I've also tried using the timeout option, and that seems to help, but it doesn't give all updates (same behavior as #1802) and typically returns about 1/2 of the updates each time.

Is this a defect, or am I using `poll` incorrectly? Is there an expectation that it be called within a specific interval?

**Comment by jeffwidman** [comment] 2019-05-29 08:01
I'm working on my test suite at work for our internal wrapper of `kafka-python` and just ran across something very similar. 

The gist of it is that when it gets triggered, it leaves it in a state where `consumer.poll()` returns nothing, yet I see `consumer.highwater()` and `consumer.position()` increasing as I produce more messages... 

kafka-python: 1.4.6
kafka broker: 1.0.1

I'm trying to extract a code snippet that triggers this without our work wrapper...

**Comment by jeffwidman** [comment] 2019-05-29 17:16
Here's more details of what I'm seeing--note that `consumer.poll()` results in an immediately updated `consumer.position()`, but `consumer.highwater()` takes a bit longer to update. However, `consumer.poll()` still never returns any of the messages:
```
(Pdb) topic
'test_consume_poll'
(Pdb) consumer.subscribe(topics=[topic])  # There is only a single consumer in this group
(Pdb) consumer.poll()   # force the assignment
{}
(Pdb) tp = consumer.assignment().pop()
(Pdb) tp
TopicPartition(topic=u'test_consume_poll', partition=0)  # there is only one partition in this topic
(Pdb) producer
<kafka producer at 0x7f9a62ffc390 (kwargs={'bootstrap_servers': ['172.28.0.3:9092'], 'key_serializer': <function <lambda> at 0x7f9a62ff2758>, 'value_serializer': <function <lambda> at 0x7f9a62ff2848>, 'client_id': 'producer-devserver-5793', 'api_version': (0, 10)})
(Pdb) producer.send(topic, 'h')
ProduceResult(message='h', topic='test_consume_poll', result=<kafka.producer.future.FutureRecordMetadata object at 0x7f9a62752950>)
(Pdb) producer.send(topic, 'h')
ProduceResult(message='h', topic='test_consume_poll', result=<kafka.producer.future.FutureRecordMetadata object at 0x7f9a61813710>)
(Pdb) producer.send(topic, 'h')
ProduceResult(message='h', topic='test_consume_poll', result=<kafka.producer.future.FutureRecordMetadata object at 0x7f9a61813810>)
(Pdb) producer.send(topic, 'h')
ProduceResult(message='h', topic='test_consume_poll', result=<kafka.producer.future.FutureRecordMetadata object at 0x7f9a61813910>)
(Pdb) producer.flush()
(Pdb) consumer.highwater(tp)
0
(Pdb) consumer.position(tp)
0
(Pdb) consumer.poll()
{}
(Pdb) consumer.position(tp)  # BOOM, our position jumped 4 spots, even though poll returned nothing
4
(Pdb) consumer.highwater(tp)  # weirdly, our highwater mark didn't move at all
0
(Pdb) consumer.poll()  # poll again just to be sure it's not sitting in the internal buffer
{}
(Pdb) consumer.assignment()  # verify we still have our expected assignment
set([TopicPartition(topic=u'testconsumeronsume_poll', partition=0)])
(Pdb) consumer.highwater(tp)  # now the highwater mark is up to 4, which matches position, yet poll() still hasn't returned messages
4
(Pdb) _c.poll()  # again, we still get no messages from poll()
{}
```

**Comment by jeffwidman** [comment] 2019-05-29 17:38
I noticed that as soon as I commit an offset, from that point forward the consumer starts working as expected and returning messages in `poll()`.

But until there's a committed offset, even though the consumer is subscribed and the assignment has finished _before_ I produce any messages, `consumer.poll()` will not return any messages. 

I'm using auto_offset_reset = 'latest', but even so I would have expected it to start returning messages as long as the consumer's assignment finished before messages were produced.

**Comment by jeffwidman** [comment] 2019-05-30 22:42
I'm also encountering this. 

It's a race condition that occurs when the consumers polls a partition for which it has no committed offset and `auto_offset_reset='latest'`.

When it happens, `consumer.poll()` never returns messages, no matter how many I send, until I call `commit()` and then it starts working fine.

kafka-python: 1.4.6
kafka broker: 1.0.1

Code (extracted from work code that wraps `kafka-python`, so it's not runnable as-is):
     # create a new topic with one partition--the consumer will not have a known offset
    create_temp_kafka_topics(topics=[topic])
    
    consumer.subscribe(topics=[topic])
    consumer.poll()  # required for subscribe() to result in partition assignment
    initial_assignment = consumer.assignment()  
    
    message_sent = 'a'
    producer_guaranteed_send(topic, message_sent)  # this flushes message and verifies the future succeeded
    
    message_received = consumer.poll(timeout_ms=1500)
    assert message_received == message_sent  # This will sometimes fail

    # verify before message was sent we had been assigned the partition
    # so that we eliminate auto_offset_reset expected behavior
    assert consumer.assignment() == initial_assignment

    # Weirdly, even though our consumer never returned the message in poll()
    # it did see the message because the consumer's position / highwater incremented to 1
    tp = initial_assignment.pop() # only one partition in this topic
    assert consumer.highwater(tp) == 1
    assert consumer.position(tp) == 1

    # doublecheck it's not just sitting in local buffer
    print(consumer.poll(timeout_ms=1500))

    # Weirdly, as soon as I commit my offset, any messages produced after that will be seen
    consumer.commit()
    message_sent_after_commit = 'b'
    producer_guaranteed_send(topic, message_sent_after_commit)
    assert message_sent_after_commit = consumer.poll(timeout_ms=1500)  # this always succeeds

This is a race condition. Sometimes it happens, sometimes it doesn't. When it occurs, `consumer.poll()` will never return messages until I call `consumer.commit()`, after which everything works as expected. 

It triggers fairly frequently when `auto_offset_reset='latest'`. I have never seen it when `auto_offset_reset='earliest'`.

**Comment by dpkp** [comment] 2019-09-30 16:45
> Weirdly, as soon as I commit my offset, any messages produced after that will be seen

This is expected. If you are using a consumer group and you never commit offsets, a rebalance / reassignment will cause the consumer to apply the auto-offset-reset policy (if offsets have been committed, it doesn't need to reset and will just use the committed offsets -- except, of course, if the committed offsets are stale and are no longer retained by the broker). If that policy is "latest" then you will see what appears to be message skipping.

You should leverage commit / autocommit, and/or expect the auto-offset-reset policy to get applied when there is a group rebalance.

The latest release should include some improvements to overall consumer behavior, so to the extent that this was caused by low consumer throughput or by unexpected rebalances, then you should also see improvement. But either way -- you should take steps to manage commits + reset policy.

**Closed by dpkp** 2019-09-30 16:45 UTC
