### ISSUE TITLE
time.sleep blocks heartbeat

### ISSUE THREAD

**Issue by assaf-shechter** [dpkp/kafka-python#2070] opened 2020-06-25 15:45 UTC
I am using 1.4.7 version and python 3.7, and in my code that runs while consuming a message I used "time.sleep(10)" in a certain flow, and because of that sleep the heartbeat stopped and an infinite loop was created of re-balancing, leaving and re-joining the group and re-consuming the same Kafka message.
Shouldn`t the heartbeat be in a different thread and keep going?

Log lines:

"Heartbeat failed for group <my_group_name> because it is rebalancing" Every 3 seconds
Along with "Heartbeat poll expired, leaving group"

**Comment by jeffwidman** [comment] 2020-09-17 20:37
Even with the heartbeat thread, you still have to call `poll()` frequently enough to not drop out of the consumer group. They have two timeouts... essentially one is "alive" and the other is "making progress"...

Closing as this is most likely not a bug but a misunderstanding of how Kafka works.

**Closed by jeffwidman** 2020-09-17 20:37 UTC
