### ISSUE TITLE
KAFKA-3007: max.poll.records

### ISSUE THREAD

**Issue by madope** [dpkp/kafka-python#823] opened 2016-08-31 10:29 UTC
when dose kaka-python support max.poll.records option？
thx

**Comment by dpkp** [comment] 2016-08-31 15:23
It hasn't been high priority since the message iterator should provide the same benefit and it's more pythonic to boot.

Nonetheless, I think I'll probably attempt to land something in the next few months.

**Comment by dpkp** [comment] 2016-09-20 04:06
duplicate of #592

**Closed by dpkp** 2016-09-20 04:06 UTC
