### ISSUE TITLE
long processing consumer restart will stall

### ISSUE THREAD

**Issue by dalejin2014** [dpkp/kafka-python#816] opened 2016-08-24 22:35 UTC
We have a long processing consumer. Whenever a new consumer tries to join the group while the long processing consumer is processing, the new consumer will stall.
If we kill the long processing consumer and restart it again, it will stall both consumers.
When we kill the long processing consumer, that consumer tries to issue a leaveGroup command but it will fail seemingly due to the client request timeout.
When we try to start the long processing consumer again, it seems to be sending topic metadata to the broker then the subsequent join group request is issued and returning a future but when I check the server log I don't see the corresponding request in kafka-request.log.
When we construct the consumer, we have the following code:

```
        self.consumer = KafkaConsumer(bootstrap_servers=bootstrap_servers,
                                      value_deserializer=deserializer,
                                      group_id=self.user_defined_sub_name,
                                      heartbeat_interval_ms=10000,
                                      session_timeout_ms=300000,
                                      enable_auto_commit=False)
```

on the server side, we use 0.10.0.0 with default settings.
looks like a `RebalanceInProgressError` is thrown

``````
2016-08-22 20:39:08,984 - kafka.coordinator - INFO - Discovered coordinator 100 for group v1.user.queue
2016-08-22 20:39:08,984 - kafka.coordinator.consumer - INFO - Revoking previously assigned partitions set() for group v1.user.queue
2016-08-22 20:39:08,990 - kafka.cluster - DEBUG - Updated cluster metadata to ClusterMetadata(brokers: 1, topics: 1, groups: 1)
2016-08-22 20:39:08,990 - kafka.coordinator - INFO - (Re-)joining group v1.user.queue
2016-08-22 20:39:08,990 - kafka.coordinator - DEBUG - Sending JoinGroup (JoinGroupRequest_v0(group='v1.user.queue', session_timeout=300000, member_id='', protocol_type='consumer', group_protocols=[(protocol_name='range', protocol_metadata=b'\x00\x00\x00\x00\x00\x01\x00\x1av1.messagingtest.user_info\x00\x00\x00\x00'), (protocol_name='roundrobin', protocol_metadata=b'\x00\x00\x00\x00\x00\x01\x00\x1av1.messagingtest.user_info\x00\x00\x00\x00')])) to coordinator 100
2016-08-22 20:39:08,991 - kafka.conn - DEBUG - <BrokerConnection host=10.128.64.81/10.128.64.81 port=9092> Request 5: JoinGroupRequest_v0(group='v1.user.queue', session_timeout=300000, member_id='', protocol_type='consumer', group_protocols=[(protocol_name='range', protocol_metadata=b'\x00\x00\x00\x00\x00\x01\x00\x1av1.messagingtest.user_info\x00\x00\x00\x00'), (protocol_name='roundrobin', protocol_metadata=b'\x00\x00\x00\x00\x00\x01\x00\x1av1.messagingtest.user_info\x00\x00\x00\x00')])
2016-08-22 20:43:04,576 - kafka.conn - WARNING - <BrokerConnection host=10.128.64.81/10.128.64.81 port=9092> timed out after 40000 ms. Closing connection.
2016-08-22 20:43:04,576 - kafka.client - WARNING - Node 100 connection failed – refreshing metadata
2016-08-22 20:43:04,576 - kafka.coordinator - ERROR - Error sending JoinGroupRequest_v0 to node 100 [Error 7 RequestTimedOutError: Request timed out after 40000 ms]
2016-08-22 20:43:04,576 - kafka.coordinator - WARNING - Marking the coordinator dead (node 100) for group v1.user.queue: None.
2016-08-22 20:43:04,678 - kafka.coordinator - DEBUG - Sending group coordinator request for group v1.user.queue to broker 100```
``````

**Comment by ilaif** [comment] 2016-09-21 17:20
@dalejin2014 Did you solve this? I'm getting this too, and it's a real pain.

**Comment by relyt0925** [comment] 2016-10-06 19:00
@dalejin2014 Any comment on this? I am experiencing an issue where the socket is getting closed and the _sock() is turned to None and then an Exception is thrown because NoneType has no attribute .setblocking()

**Comment by abc100m** [comment] 2016-12-28 10:23
kafka-python version: kafka-python (1.3.1)
kafka broker: 0.9


We have this same issue?  when  "_Node 1 connection failed -- refreshing metadata_" occurred then kafka-python will not working,  and  the App works well after restart.

This App  running from 2016-09-24 to 2016-12-28 16:53

error log:
```shell
[2016-12-28 16:53:28,353] [WARNING] [kafka-python-producer-1-network-thread] Node 1 connection failed -- refreshing metadata



[2016-12-28 18:08:10,054] [INFO] [MainThread] Broker is not v(0, 10) -- it did not recognize ApiVersionRequest_v0
[2016-12-28 18:08:10,215] [INFO] [MainThread] Broker version identifed as 0.9
[2016-12-28 18:08:10,216] [INFO] [MainThread] Set configuration api_version=(0, 9) to skip auto check_version requests on startup
[2016-12-28 18:08:10,218] [INFO] [MainThread] Updating subscribed topics to: ('QDP_LAOLAI_CHECK',)
[2016-12-28 18:08:10,392] [INFO] [MainThread] Broker is not v(0, 10) -- it did not recognize ApiVersionRequest_v0
[2016-12-28 18:08:10,559] [INFO] [MainThread] Broker version identifed as 0.9
[2016-12-28 18:08:10,559] [INFO] [MainThread] Set configuration api_version=(0, 9) to skip auto check_version requests on startup
```

**Comment by dpkp** [comment] 2016-12-28 23:53
I agree this is very troublesome. I haven't been able to reproduce exactly. But while trying to debug I found several small bugs that may have been conspiring: #887 and #896 . I also tried to improve logging re Group Coordinator in #890 since this seems to be an issue w/ group coordination. Have you tried these fixes from master? I am planning to publish 1.3.2 shortly and perhaps you can see if they fix your issue?

**Comment by mohyt** [comment] 2017-04-24 07:40
I have move to kafka-python 1.3.3 but still facing same issue. Do we have fix for this ?

**Comment by CesarLanderos** [comment] 2017-08-24 16:25
we also have this problem too, we used to just restart the consumer container to "fix" that, but now it never processes the messages again.

**Comment by jeffwidman** [comment] 2017-08-28 18:15
@CesarLanderos are your offsets getting incremented? That would explain the never processing messages again, and would likely not be related to this error.

**Closed** 2020-02-12 21:28 UTC
