### ISSUE TITLE
Error processing callback 'FetchResponse_v1' object has no attribute '__getitem__'

### ISSUE THREAD

**Issue by athensofamerican** [dpkp/kafka-python#669] opened 2016-04-25 20:20 UTC
I am trying out the example.py with kafka-python 1.1.0 again a kafka 0.9 and get this error message:
Error processing callback
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/kafka/future.py", line 33, in success
    f(value)
  File "/Library/Python/2.7/site-packages/kafka/consumer/fetcher.py", line 656, in _handle_fetch_response
    self._sensors.fetch_throttle_time_sensor.record(response['throttle_time_ms'])
TypeError: 'FetchResponse_v1' object has no attribute '__getitem__'

**Comment by zackdever** [comment] 2016-04-25 20:25
Duplicate of #665, fix coming soon!

**Closed** 2016-04-25 20:30 UTC
